/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Desktop/APRESS/withnim/nimcache/regexping.o /Users/niko/Desktop/APRESS/withnim/nimcache/regexping.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A;
typedef struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
typedef NU8 tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
struct tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw {
tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A* h;
tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ* e;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_Pcre_bGVj3RgRlNY6kwJpiYI9b3A {
char dummy;
};
struct tyObject_ExtraData_aRbi7557vgG4KV47nk1CWQ {
long flags;
void* study_data;
long match_limit;
void* callout_data;
void* tables;
long match_limit_recursion;
void* mark;
void* executable_jit;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(NIM_BOOL, match_emOFZQnjweIKzqVZYIeg7Are)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start);
static N_INLINE(NI, matchLen_Dok1EtENwM9ayJsqxZJOlTQre)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize);
N_LIB_PRIVATE N_NIMCALL(int, matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, int start, int bufSize, int flags);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*, re_2TnOqvPvxix6tRYnuIeq9bw)(NimStringDesc* s, tySet_tyEnum_RegexFlag_gA189bEOtGhLt2cCHGW4ywg flags);
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_5)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_7)(void);
static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start);
N_LIB_PRIVATE N_NIMCALL(int, matchOrFind_lYP9aKTHndN56JtpfLZGvIg)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start, NI bufSize, int flags);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
static N_INLINE(NI, subInt)(NI a, NI b);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qregexping)(FILE* f, NimStringDesc** x, NI xLen_0);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_pcreDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_rtarraysDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_reDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, regexpingDatInit000)(void);
tyArray_Re75IspeoxXy2oCZHwcRrA matches_XP9arxNAKhx3zyeQUJKl39cQ;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_Re75IspeoxXy2oCZHwcRrA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NimStringDesc* s_lnolgbYjae8Os9aV59cSQUfg;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* word_AdZPbDdK3b0oYs6qLVolZA;
STRING_LITERAL(TM_kmVi5UCgkmGFNtL9aX9cOjrg_3, "abcdefg", 7);
STRING_LITERAL(TM_kmVi5UCgkmGFNtL9aX9cOjrg_4, "c(d)ef(g)", 9);
STRING_LITERAL(TM_kmVi5UCgkmGFNtL9aX9cOjrg_8, "\\d+", 3);
STRING_LITERAL(TM_kmVi5UCgkmGFNtL9aX9cOjrg_9, "00232this02939is39an22example111", 32);
STRING_LITERAL(TM_kmVi5UCgkmGFNtL9aX9cOjrg_14, "\012", 1);
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_2)(void) {
	NI T1_;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < 2; T1_++) {
	nimGCvisit((void*)matches_XP9arxNAKhx3zyeQUJKl39cQ[T1_], 0);
	}
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, matchLen_Dok1EtENwM9ayJsqxZJOlTQre)(NCSTRING buf, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start, NI bufSize) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim");
{	result = (NI)0;
	nimln_(228, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_ZplXC9aaMp1xKMHlJu8mEEg(buf, pattern, matches, matchesLen_0, ((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(bufSize, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int) 16));
	result = ((NI) (T1_));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, match_emOFZQnjweIKzqVZYIeg7Are)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NimStringDesc** matches, NI matchesLen_0, NI start) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("match", "re.nim");
	result = (NIM_BOOL)0;
	nimln_(267, "re.nim");
	nimln_(398, "system.nim");
	nimln_(267, "re.nim");
	T1_ = (NI)0;
	T1_ = matchLen_Dok1EtENwM9ayJsqxZJOlTQre(s->data, pattern, matches, matchesLen_0, start, (s ? s->Sup.len : 0));
	result = !((T1_ == ((NI) -1)));
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_5)(void) {
	nimGCvisit((void*)s_lnolgbYjae8Os9aV59cSQUfg, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}
static N_NIMCALL(void, TM_kmVi5UCgkmGFNtL9aX9cOjrg_7)(void) {
	nimGCvisit((void*)word_AdZPbDdK3b0oYs6qLVolZA, 0);
}

static N_INLINE(NI, matchLen_Qgadm9adOmbpTJaQImyB4SQre)(NimStringDesc* s, tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* pattern, NI start) {
	NI result;
	int T1_;
	nimfr_("matchLen", "re.nim");
	result = (NI)0;
	nimln_(241, "re.nim");
	T1_ = (int)0;
	T1_ = matchOrFind_lYP9aKTHndN56JtpfLZGvIg(s->data, pattern, ((NI) (((int)chckRange(start, ((int) (-2147483647 -1)), ((int) 2147483647))))), ((NI) (((int)chckRange((s ? s->Sup.len : 0), ((int) (-2147483647 -1)), ((int) 2147483647))))), ((int) 16));
	result = ((NI) (T1_));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, writeLine_rBQVO3cm3BhnA9aEFD7PG6Qregexping)(FILE* f, NimStringDesc** x, NI xLen_0) {
	nimfr_("writeLine", "sysio.nim");
	{
		NimStringDesc* i;
		NI i_2;
		i = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				if (!(i_2 < xLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				i = x[i_2];
				nimln_(274, "sysio.nim");
				write_c4mGyJBvK73pdM22jiweKQ(f, i);
				nimln_(2188, "system.nim");
				i_2 += ((NI) 1);
			} LA3: ;
		}
	}
	nimln_(275, "sysio.nim");
	write_c4mGyJBvK73pdM22jiweKQ(f, ((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_14));
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_pcreDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_rtarraysDatInit000();
	stdlib_reDatInit000();
	regexpingDatInit000();
	stdlib_pcreInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_rtarraysInit000();
	stdlib_reInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("regexping", "regexping.nim");
nimRegisterGlobalMarker(TM_kmVi5UCgkmGFNtL9aX9cOjrg_2);
nimRegisterGlobalMarker(TM_kmVi5UCgkmGFNtL9aX9cOjrg_5);
nimRegisterGlobalMarker(TM_kmVi5UCgkmGFNtL9aX9cOjrg_7);
	nimln_(4, "regexping.nim");
	{
		tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* T3_;
		NIM_BOOL T4_;
		T3_ = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
		T3_ = re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_4), 16);
		T4_ = (NIM_BOOL)0;
		T4_ = match_emOFZQnjweIKzqVZYIeg7Are(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_3), T3_, matches_XP9arxNAKhx3zyeQUJKl39cQ, 2, ((NI) 2));
		if (!T4_) goto LA5_;
		{
			NI i;
			nimln_(2199, "system.nim");
			i = ((NI) 0);
			nimln_(2200, "system.nim");
			{
				if (!(((NI) (i)) <= ((NI) 1))) goto LA10_;
				{
					nimln_(2201, "system.nim");
					while (1) {
						NimStringDesc* T14_;
						tyArray_nHXaesL0DJZHyVS07ARPRA T15_;
						NI TM_kmVi5UCgkmGFNtL9aX9cOjrg_6;
						nimln_(2202, "system.nim");
						T14_ = (NimStringDesc*)0;
						T14_ = s_lnolgbYjae8Os9aV59cSQUfg; s_lnolgbYjae8Os9aV59cSQUfg = copyStringRC1(matches_XP9arxNAKhx3zyeQUJKl39cQ[(i)- 0]);
						if (T14_) nimGCunrefNoCycle(T14_);
						nimln_(6, "regexping.nim");
						memset((void*)T15_, 0, sizeof(T15_));
						T15_[0] = copyString(s_lnolgbYjae8Os9aV59cSQUfg);
						echoBinSafe(T15_, 1);
						nimln_(2203, "system.nim");
						{
							if (!(((NI) 1) <= ((NI) (i)))) goto LA18_;
							goto LA12;
						}
						LA18_: ;
						nimln_(2204, "system.nim");
						TM_kmVi5UCgkmGFNtL9aX9cOjrg_6 = addInt(i, ((NI) 1));
						if (TM_kmVi5UCgkmGFNtL9aX9cOjrg_6 < 0 || TM_kmVi5UCgkmGFNtL9aX9cOjrg_6 > 1) raiseOverflow();
						i = (NI)(TM_kmVi5UCgkmGFNtL9aX9cOjrg_6);
					}
				} LA12: ;
			}
			LA10_: ;
		}
	}
	LA5_: ;
	{
		tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw* colontmp_;
		NI first;
		NI last;
		colontmp_ = (tyObject_RegexDesc_jxMAPyr9aBYX9b0g7iZ2E8zw*)0;
		nimln_(9, "regexping.nim");
		colontmp_ = re_2TnOqvPvxix6tRYnuIeq9bw(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_8), 16);
		nimln_(528, "re.nim");
		first = ((NI) -1);
		nimln_(529, "re.nim");
		last = ((NI) -1);
		{
			nimln_(530, "re.nim");
			while (1) {
				NI x;
				if (!(last < ((NI) 32))) goto LA22;
				nimln_(531, "re.nim");
				x = matchLen_Qgadm9adOmbpTJaQImyB4SQre(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_9), colontmp_, last);
				nimln_(532, "re.nim");
				{
					NI TM_kmVi5UCgkmGFNtL9aX9cOjrg_10;
					if (!(((NI) 0) < x)) goto LA25_;
					TM_kmVi5UCgkmGFNtL9aX9cOjrg_10 = addInt(last, x);
					last = (NI)(TM_kmVi5UCgkmGFNtL9aX9cOjrg_10);
				}
				LA25_: ;
				nimln_(533, "re.nim");
				first = last;
				nimln_(534, "re.nim");
				{
					NI TM_kmVi5UCgkmGFNtL9aX9cOjrg_11;
					if (!(x == ((NI) 0))) goto LA29_;
					TM_kmVi5UCgkmGFNtL9aX9cOjrg_11 = addInt(last, ((NI) 1));
					last = (NI)(TM_kmVi5UCgkmGFNtL9aX9cOjrg_11);
				}
				LA29_: ;
				{
					nimln_(535, "re.nim");
					while (1) {
						NI TM_kmVi5UCgkmGFNtL9aX9cOjrg_12;
						if (!(last < ((NI) 32))) goto LA32;
						nimln_(9, "regexping.nim");
						x = matchLen_Qgadm9adOmbpTJaQImyB4SQre(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_9), colontmp_, last);
						nimln_(537, "re.nim");
						{
							if (!(((NI) 0) <= x)) goto LA35_;
							goto LA31;
						}
						LA35_: ;
						nimln_(538, "re.nim");
						TM_kmVi5UCgkmGFNtL9aX9cOjrg_12 = addInt(last, ((NI) 1));
						last = (NI)(TM_kmVi5UCgkmGFNtL9aX9cOjrg_12);
					} LA32: ;
				} LA31: ;
				nimln_(539, "re.nim");
				{
					NI TM_kmVi5UCgkmGFNtL9aX9cOjrg_13;
					tyArray_nHXaesL0DJZHyVS07ARPRA T41_;
					if (!(first <= last)) goto LA39_;
					nimln_(9, "regexping.nim");
					nimln_(540, "re.nim");
					TM_kmVi5UCgkmGFNtL9aX9cOjrg_13 = subInt(last, ((NI) 1));
					asgnRefNoCycle((void**) (&word_AdZPbDdK3b0oYs6qLVolZA), copyStrLast(((NimStringDesc*) &TM_kmVi5UCgkmGFNtL9aX9cOjrg_9), first, (NI)(TM_kmVi5UCgkmGFNtL9aX9cOjrg_13)));
					nimln_(10, "regexping.nim");
					memset((void*)T41_, 0, sizeof(T41_));
					T41_[0] = copyString(word_AdZPbDdK3b0oYs6qLVolZA);
					writeLine_rBQVO3cm3BhnA9aEFD7PG6Qregexping(stdout, T41_, 1);
				}
				LA39_: ;
			} LA22: ;
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, regexpingDatInit000)(void) {
NTI_Re75IspeoxXy2oCZHwcRrA_.size = sizeof(tyArray_Re75IspeoxXy2oCZHwcRrA);
NTI_Re75IspeoxXy2oCZHwcRrA_.kind = 16;
NTI_Re75IspeoxXy2oCZHwcRrA_.base = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
NTI_Re75IspeoxXy2oCZHwcRrA_.flags = 2;
}

