/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_base64.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_base64.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encode_8tc7ShUv28tbkkCiLVvt1g)(NimStringDesc* s, NI lineLen, NimStringDesc* newLine);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, decodeByte_aRI3ma9crc7s6AqVz02rowgbase64)(NIM_CHAR b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decode_XT59bN9bp4Q8hPMmY9cQ9aRuKQ)(NimStringDesc* s);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_2L6xrRPz7CWDB3T1R9cDN5A_14, "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+"
"/", 64);
STRING_LITERAL(TM_2L6xrRPz7CWDB3T1R9cDN5A_24, "len(a) == L string modified while iterating over it", 51);
NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw Whitespace_DBsaoPRHprqd3sCE9ajSEHw = {
0x00, 0x3E, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_2L6xrRPz7CWDB3T1R9cDN5A_52, "i == len(s) ", 12);

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encode_8tc7ShUv28tbkkCiLVvt1g)(NimStringDesc* s, NI lineLen, NimStringDesc* newLine) {
	NimStringDesc* result;
	NI total;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_2;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_3;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_4;
	NI numLines;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_5;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_6;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_7;
	NI i;
	NI r;
	NI currLine;
	nimfr_("encode", "base64.nim");
	result = (NimStringDesc*)0;
	nimln_(50, "base64.nim");
	nimln_(115, "base64.nim");
	TM_2L6xrRPz7CWDB3T1R9cDN5A_2 = addInt((s ? s->Sup.len : 0), ((NI) 2));
	TM_2L6xrRPz7CWDB3T1R9cDN5A_3 = divInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_2), ((NI) 3));
	TM_2L6xrRPz7CWDB3T1R9cDN5A_4 = mulInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_3), ((NI) 4));
	total = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_4);
	nimln_(51, "base64.nim");
	TM_2L6xrRPz7CWDB3T1R9cDN5A_5 = addInt(total, lineLen);
	TM_2L6xrRPz7CWDB3T1R9cDN5A_6 = subInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_5), ((NI) 1));
	TM_2L6xrRPz7CWDB3T1R9cDN5A_7 = divInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_6), lineLen);
	numLines = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_7);
	nimln_(52, "base64.nim");
	{
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_8;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_9;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_10;
		if (!(((NI) 0) < numLines)) goto LA3_;
		TM_2L6xrRPz7CWDB3T1R9cDN5A_8 = subInt(numLines, ((NI) 1));
		nimln_(115, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_9 = mulInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_8), (newLine ? newLine->Sup.len : 0));
		TM_2L6xrRPz7CWDB3T1R9cDN5A_10 = addInt(total, (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_9));
		total = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_10);
	}
	LA3_: ;
	nimln_(54, "base64.nim");
	result = mnewString(((NI)chckRange(total, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(56, "base64.nim");
	i = ((NI) 0);
	nimln_(57, "base64.nim");
	r = ((NI) 0);
	nimln_(58, "base64.nim");
	currLine = ((NI) 0);
	{
		nimln_(59, "base64.nim");
		while (1) {
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_11;
			NI a;
			NI b;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_12;
			NI c;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_13;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_15;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_16;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_17;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_18;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_19;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_20;
			nimln_(115, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_11 = subInt((s ? s->Sup.len : 0), ((NI) 2));
			if (!(i < (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_11))) goto LA6;
			nimln_(61, "base64.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			a = ((NU8)(s->data[i]));
			nimln_(62, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_12 = addInt(i, ((NI) 1));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_12)) > (NU)(s->Sup.len)) raiseIndexError();
			b = ((NU8)(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_12)]));
			nimln_(63, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_13 = addInt(i, ((NI) 2));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_13)) > (NU)(s->Sup.len)) raiseIndexError();
			c = ((NU8)(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_13)]));
			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
			nimln_(64, "base64.nim");
			if ((NU)((NI)((NU64)(a) >> (NU64)(((NI) 2)))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
			result->data[r] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NU64)(a) >> (NU64)(((NI) 2)))];
			nimln_(65, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_15 = addInt(r, ((NI) 1));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_15)) > (NU)(result->Sup.len)) raiseIndexError();
			if ((NU)((NI)((NI)((NU64)((NI)(a & ((NI) 3))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(b & ((NI) 240))) >> (NU64)(((NI) 4))))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
			result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_15)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NI)((NU64)((NI)(a & ((NI) 3))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(b & ((NI) 240))) >> (NU64)(((NI) 4))))];
			nimln_(66, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_16 = addInt(r, ((NI) 2));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_16)) > (NU)(result->Sup.len)) raiseIndexError();
			if ((NU)((NI)((NI)((NU64)((NI)(b & ((NI) 15))) << (NU64)(((NI) 2))) | (NI)((NU64)((NI)(c & ((NI) 192))) >> (NU64)(((NI) 6))))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
			result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_16)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NI)((NU64)((NI)(b & ((NI) 15))) << (NU64)(((NI) 2))) | (NI)((NU64)((NI)(c & ((NI) 192))) >> (NU64)(((NI) 6))))];
			nimln_(67, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_17 = addInt(r, ((NI) 3));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_17)) > (NU)(result->Sup.len)) raiseIndexError();
			if ((NU)((NI)(c & ((NI) 63))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
			result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_17)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)(c & ((NI) 63))];
			nimln_(68, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_18 = addInt(r, ((NI) 4));
			r = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_18);
			nimln_(69, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_19 = addInt(i, ((NI) 3));
			i = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_19);
			nimln_(70, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_20 = addInt(currLine, ((NI) 4));
			currLine = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_20);
			nimln_(72, "base64.nim");
			{
				NIM_BOOL T9_;
				NIM_BOOL T10_;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_21;
				T9_ = (NIM_BOOL)0;
				T10_ = (NIM_BOOL)0;
				nimln_(115, "base64.nim");
				T10_ = (lineLen <= currLine);
				if (!(T10_)) goto LA11_;
				nimln_(398, "system.nim");
				nimln_(72, "base64.nim");
				nimln_(115, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_21 = subInt((s ? s->Sup.len : 0), ((NI) 2));
				T10_ = !((i == (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_21)));
				LA11_: ;
				T9_ = T10_;
				if (!(T9_)) goto LA12_;
				nimln_(72, "base64.nim");
				T9_ = (r < total);
				LA12_: ;
				if (!T9_) goto LA13_;
				{
					NIM_CHAR x;
					NI i_2;
					NI L;
					x = (NIM_CHAR)0;
					nimln_(3823, "system.nim");
					i_2 = ((NI) 0);
					nimln_(3824, "system.nim");
					L = (newLine ? newLine->Sup.len : 0);
					{
						nimln_(3825, "system.nim");
						while (1) {
							NI TM_2L6xrRPz7CWDB3T1R9cDN5A_22;
							NI TM_2L6xrRPz7CWDB3T1R9cDN5A_23;
							if (!(i_2 < L)) goto LA17;
							nimln_(3826, "system.nim");
							if ((NU)(i_2) > (NU)(newLine->Sup.len)) raiseIndexError();
							x = newLine->data[i_2];
							if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
							nimln_(74, "base64.nim");
							result->data[r] = x;
							nimln_(75, "base64.nim");
							TM_2L6xrRPz7CWDB3T1R9cDN5A_22 = addInt(r, ((NI) 1));
							r = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_22);
							nimln_(3827, "system.nim");
							TM_2L6xrRPz7CWDB3T1R9cDN5A_23 = addInt(i_2, ((NI) 1));
							i_2 = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_23);
							nimln_(3828, "system.nim");
							{
								if (!!(((newLine ? newLine->Sup.len : 0) == L))) goto LA20_;
								failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_24));
							}
							LA20_: ;
						} LA17: ;
					}
				}
				nimln_(76, "base64.nim");
				currLine = ((NI) 0);
			}
			LA13_: ;
		} LA6: ;
	}
	nimln_(115, "base64.nim");
	{
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_25;
		NI a_2;
		NI b_2;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_26;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_27;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_28;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_29;
		nimln_(78, "base64.nim");
		nimln_(115, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_25 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		if (!(i < (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_25))) goto LA24_;
		nimln_(80, "base64.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		a_2 = ((NU8)(s->data[i]));
		nimln_(81, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_26 = addInt(i, ((NI) 1));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_26)) > (NU)(s->Sup.len)) raiseIndexError();
		b_2 = ((NU8)(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_26)]));
		if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
		nimln_(82, "base64.nim");
		if ((NU)((NI)((NU64)(a_2) >> (NU64)(((NI) 2)))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
		result->data[r] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NU64)(a_2) >> (NU64)(((NI) 2)))];
		nimln_(83, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_27 = addInt(r, ((NI) 1));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_27)) > (NU)(result->Sup.len)) raiseIndexError();
		if ((NU)((NI)((NI)((NU64)((NI)(a_2 & ((NI) 3))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(b_2 & ((NI) 240))) >> (NU64)(((NI) 4))))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_27)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NI)((NU64)((NI)(a_2 & ((NI) 3))) << (NU64)(((NI) 4))) | (NI)((NU64)((NI)(b_2 & ((NI) 240))) >> (NU64)(((NI) 4))))];
		nimln_(84, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_28 = addInt(r, ((NI) 2));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_28)) > (NU)(result->Sup.len)) raiseIndexError();
		if ((NU)((NI)((NU64)((NI)(b_2 & ((NI) 15))) << (NU64)(((NI) 2)))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_28)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NU64)((NI)(b_2 & ((NI) 15))) << (NU64)(((NI) 2)))];
		nimln_(85, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_29 = addInt(r, ((NI) 3));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_29)) > (NU)(result->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_29)] = 61;
		nimln_(86, "base64.nim");
		{
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_30;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_31;
			nimln_(398, "system.nim");
			nimln_(86, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_30 = addInt(r, ((NI) 4));
			if (!!(((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_30) == (result ? result->Sup.len : 0)))) goto LA28_;
			nimln_(87, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_31 = addInt(r, ((NI) 4));
			result = setLengthStr(result, ((NI)chckRange((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_31), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
		LA28_: ;
	}
	goto LA22_;
	LA24_: ;
	{
		NI a_3;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_32;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_33;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_34;
		nimln_(88, "base64.nim");
		nimln_(115, "base64.nim");
		if (!(i < (s ? s->Sup.len : 0))) goto LA31_;
		nimln_(89, "base64.nim");
		if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
		a_3 = ((NU8)(s->data[i]));
		if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
		nimln_(90, "base64.nim");
		if ((NU)((NI)((NU64)(a_3) >> (NU64)(((NI) 2)))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
		result->data[r] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NU64)(a_3) >> (NU64)(((NI) 2)))];
		nimln_(91, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_32 = addInt(r, ((NI) 1));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_32)) > (NU)(result->Sup.len)) raiseIndexError();
		if ((NU)((NI)((NU64)((NI)(a_3 & ((NI) 3))) << (NU64)(((NI) 4)))) > (NU)(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_32)] = ((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_14)->data[(NI)((NU64)((NI)(a_3 & ((NI) 3))) << (NU64)(((NI) 4)))];
		nimln_(92, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_33 = addInt(r, ((NI) 2));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_33)) > (NU)(result->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_33)] = 61;
		nimln_(93, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_34 = addInt(r, ((NI) 3));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_34)) > (NU)(result->Sup.len)) raiseIndexError();
		result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_34)] = 61;
		nimln_(94, "base64.nim");
		{
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_35;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_36;
			nimln_(398, "system.nim");
			nimln_(94, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_35 = addInt(r, ((NI) 4));
			if (!!(((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_35) == (result ? result->Sup.len : 0)))) goto LA35_;
			nimln_(95, "base64.nim");
			TM_2L6xrRPz7CWDB3T1R9cDN5A_36 = addInt(r, ((NI) 4));
			result = setLengthStr(result, ((NI)chckRange((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_36), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
		LA35_: ;
	}
	goto LA22_;
	LA31_: ;
	{
		nimln_(97, "base64.nim");
		{
			nimln_(398, "system.nim");
			nimln_(97, "base64.nim");
			if (!!((r == (result ? result->Sup.len : 0)))) goto LA40_;
			nimln_(98, "base64.nim");
			result = setLengthStr(result, ((NI)chckRange(r, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
		LA40_: ;
	}
	LA22_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, decodeByte_aRI3ma9crc7s6AqVz02rowgbase64)(NIM_CHAR b) {
	NI result;
	nimfr_("decodeByte", "base64.nim");
	result = (NI)0;
	nimln_(118, "base64.nim");
	switch (((NU8)(b))) {
	case 43:
	{
		nimln_(119, "base64.nim");
		result = ((NI) 62);
	}
	break;
	case 48 ... 57:
	{
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_37;
		nimln_(120, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_37 = addInt(((NU8)(b)), ((NI) 4));
		result = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_37);
	}
	break;
	case 65 ... 90:
	{
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_38;
		nimln_(121, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_38 = subInt(((NU8)(b)), ((NI) 65));
		result = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_38);
	}
	break;
	case 97 ... 122:
	{
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_39;
		nimln_(122, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_39 = subInt(((NU8)(b)), ((NI) 71));
		result = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_39);
	}
	break;
	default:
	{
		nimln_(123, "base64.nim");
		result = ((NI) 63);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decode_XT59bN9bp4Q8hPMmY9cQ9aRuKQ)(NimStringDesc* s) {
	NimStringDesc* result;
	NI total;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_40;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_41;
	NI TM_2L6xrRPz7CWDB3T1R9cDN5A_42;
	NI i;
	NI r;
	nimfr_("decode", "base64.nim");
	result = (NimStringDesc*)0;
	nimln_(129, "base64.nim");
	TM_2L6xrRPz7CWDB3T1R9cDN5A_40 = addInt((s ? s->Sup.len : 0), ((NI) 3));
	TM_2L6xrRPz7CWDB3T1R9cDN5A_41 = divInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_40), ((NI) 4));
	TM_2L6xrRPz7CWDB3T1R9cDN5A_42 = mulInt((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_41), ((NI) 3));
	total = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_42);
	nimln_(131, "base64.nim");
	result = mnewString(((NI)chckRange(total, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(134, "base64.nim");
	i = ((NI) 0);
	nimln_(135, "base64.nim");
	r = ((NI) 0);
	{
		nimln_(136, "base64.nim");
		while (1) {
			{
				nimln_(137, "base64.nim");
				while (1) {
					NI TM_2L6xrRPz7CWDB3T1R9cDN5A_43;
					if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
					if (!(((NU8)(s->data[i])) == ((NU8)(32)) || ((NU8)(s->data[i])) == ((NU8)(9)) || ((NU8)(s->data[i])) == ((NU8)(11)) || ((NU8)(s->data[i])) == ((NU8)(13)) || ((NU8)(s->data[i])) == ((NU8)(10)) || ((NU8)(s->data[i])) == ((NU8)(12)))) goto LA4;
					TM_2L6xrRPz7CWDB3T1R9cDN5A_43 = addInt(i, ((NI) 1));
					i = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_43);
				} LA4: ;
			}
			nimln_(138, "base64.nim");
			{
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_44;
				NI a;
				NI b;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_45;
				NI c;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_46;
				NI d;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_47;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_48;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_49;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_50;
				NI TM_2L6xrRPz7CWDB3T1R9cDN5A_51;
				TM_2L6xrRPz7CWDB3T1R9cDN5A_44 = subInt((s ? s->Sup.len : 0), ((NI) 3));
				if (!(i < (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_44))) goto LA7_;
				nimln_(140, "base64.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				a = decodeByte_aRI3ma9crc7s6AqVz02rowgbase64(s->data[i]);
				nimln_(141, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_45 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_45)) > (NU)(s->Sup.len)) raiseIndexError();
				b = decodeByte_aRI3ma9crc7s6AqVz02rowgbase64(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_45)]);
				nimln_(142, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_46 = addInt(i, ((NI) 2));
				if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_46)) > (NU)(s->Sup.len)) raiseIndexError();
				c = decodeByte_aRI3ma9crc7s6AqVz02rowgbase64(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_46)]);
				nimln_(143, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_47 = addInt(i, ((NI) 3));
				if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_47)) > (NU)(s->Sup.len)) raiseIndexError();
				d = decodeByte_aRI3ma9crc7s6AqVz02rowgbase64(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_47)]);
				if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(145, "base64.nim");
				result->data[r] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NI)((NU64)(a) << (NU64)(((NI) 2))) & ((NI) 255)) | (NI)((NI)((NU64)(b) >> (NU64)(((NI) 4))) & ((NI) 3))), ((NI) 0), ((NI) 255)))));
				nimln_(146, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_48 = addInt(r, ((NI) 1));
				if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_48)) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_48)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NI)((NU64)(b) << (NU64)(((NI) 4))) & ((NI) 255)) | (NI)((NI)((NU64)(c) >> (NU64)(((NI) 2))) & ((NI) 15))), ((NI) 0), ((NI) 255)))));
				nimln_(147, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_49 = addInt(r, ((NI) 2));
				if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_49)) > (NU)(result->Sup.len)) raiseIndexError();
				result->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_49)] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NI)((NU64)(c) << (NU64)(((NI) 6))) & ((NI) 255)) | (NI)(d & ((NI) 63))), ((NI) 0), ((NI) 255)))));
				nimln_(148, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_50 = addInt(r, ((NI) 3));
				r = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_50);
				nimln_(149, "base64.nim");
				TM_2L6xrRPz7CWDB3T1R9cDN5A_51 = addInt(i, ((NI) 4));
				i = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_51);
			}
			goto LA5_;
			LA7_: ;
			{
				nimln_(150, "base64.nim");
				goto LA1;
			}
			LA5_: ;
		}
	} LA1: ;
	nimln_(151, "base64.nim");
	{
		if (!!((i == (s ? s->Sup.len : 0)))) goto LA12_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_2L6xrRPz7CWDB3T1R9cDN5A_52));
	}
	LA12_: ;
	nimln_(153, "base64.nim");
	{
		NIM_BOOL T16_;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_53;
		NI TM_2L6xrRPz7CWDB3T1R9cDN5A_54;
		T16_ = (NIM_BOOL)0;
		T16_ = (((NI) 0) < i);
		if (!(T16_)) goto LA17_;
		TM_2L6xrRPz7CWDB3T1R9cDN5A_53 = subInt(i, ((NI) 1));
		if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_53)) > (NU)(s->Sup.len)) raiseIndexError();
		T16_ = ((NU8)(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_53)]) == (NU8)(61));
		LA17_: ;
		if (!T16_) goto LA18_;
		nimln_(154, "base64.nim");
		TM_2L6xrRPz7CWDB3T1R9cDN5A_54 = subInt(r, ((NI) 1));
		r = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_54);
		nimln_(155, "base64.nim");
		{
			NIM_BOOL T22_;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_55;
			NI TM_2L6xrRPz7CWDB3T1R9cDN5A_56;
			T22_ = (NIM_BOOL)0;
			T22_ = (((NI) 1) < i);
			if (!(T22_)) goto LA23_;
			TM_2L6xrRPz7CWDB3T1R9cDN5A_55 = subInt(i, ((NI) 2));
			if ((NU)((NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_55)) > (NU)(s->Sup.len)) raiseIndexError();
			T22_ = ((NU8)(s->data[(NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_55)]) == (NU8)(61));
			LA23_: ;
			if (!T22_) goto LA24_;
			TM_2L6xrRPz7CWDB3T1R9cDN5A_56 = subInt(r, ((NI) 1));
			r = (NI)(TM_2L6xrRPz7CWDB3T1R9cDN5A_56);
		}
		LA24_: ;
	}
	LA18_: ;
	nimln_(156, "base64.nim");
	result = setLengthStr(result, ((NI)chckRange(r, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_base64Init000)(void) {
	nimfr_("base64", "base64.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_base64DatInit000)(void) {
}

