/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_nativesockets.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_nativesockets.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <string.h>
#include <netinet/in.h>
#include <unistd.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <sys/select.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Hostent_azV1qb29cFIFe582aezrNAQ tyObject_Hostent_azV1qb29cFIFe582aezrNAQ;
typedef struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ;
typedef struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_J0FzjuY02DFObU1sQZLwJA tyTuple_J0FzjuY02DFObU1sQZLwJA;
typedef struct tySequence_9apztJSmgERYU8fZOjI4pOg tySequence_9apztJSmgERYU8fZOjI4pOg;
typedef struct tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg;
struct tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ {
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val;
NIM_BOOL has;
};
typedef NU8 tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw;
typedef NU8 tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ {
NimStringDesc* name;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
NU16 port;
NimStringDesc* proto;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Hostent_azV1qb29cFIFe582aezrNAQ {
NimStringDesc* name;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* aliases;
tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg addrtype;
NI length;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* addrList;
};
typedef NIM_CHAR tyArray_Wfh9bjgBQ4UqJsyISUuDSuA[16];
typedef NIM_CHAR tyArray_dTlC27m9c9aWd5dvuePYanug[256];
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg {
  Exception Sup;
};
struct tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ {
  tyObject_SystemError_Fjf9b9b2IlzRO2tspHxG3tgg Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_J0FzjuY02DFObU1sQZLwJA {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ {
int Field0;
NimStringDesc* Field1;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_9apztJSmgERYU8fZOjI4pOg {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, toKnownDomain_WoQ5UOyB2HAIoN15dknZCw)(int family);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, some_JMiA9ccATJp8JunIrSlndYA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg val);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, none_IBO7fiOVpMVOmhrZWFqq1A)(void);
N_LIB_PRIVATE N_NIMCALL(int, toInt_0zBaW59cZQJVrz1L13Wid5g)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ);
N_LIB_PRIVATE N_NIMCALL(int, toInt_slGFLM9cFJ086GOC2tjJphw)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p);
N_LIB_PRIVATE N_NIMCALL(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw, toSockType_zz9bxu9cRa00a9b6j4pehnFgQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_P59cS8yz3VHsnoN6zylI5Lg)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_xsLKpyGLgUgaTjiALlo5Kw)(int domain, int sockType, int protocol);
N_LIB_PRIVATE N_NIMCALL(int, newNativeSocket_P59cS8yz3VHsnoN6zylI5Lg_2)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NIMCALL(int, newNativeSocket_xsLKpyGLgUgaTjiALlo5Kw_2)(int domain, int sockType, int protocol);
N_LIB_PRIVATE N_NIMCALL(void, close_ODRNWwddsp7NVetdw9cXCVg)(int socket);
N_LIB_PRIVATE N_NIMCALL(int, bindAddr_zpvqU0KQkzbkoKaehnMX2A)(int socket, struct sockaddr* name, socklen_t namelen);
N_LIB_PRIVATE N_NIMCALL(int, listen_BNAD35QpM7R1C7EJRtAZ3Q)(int socket, int backlog);
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__rzAI8EMyNBAQwGODeohhAA)(NU64 x);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError_bEwAamo1N7TKcaU9akpiyIg)(NI32 errorCode, NimStringDesc* additionalInfo);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError_tNPXXFl9cb3BG0pJKzUn9bew)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(void, dealloc_o4AP9bp2a6Md29bi289aWTZew)(struct addrinfo* ai);
N_LIB_PRIVATE N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x);
N_LIB_PRIVATE N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x);
N_LIB_PRIVATE N_NIMCALL(void, getServByName_NNxs1hil5R9bGsNpctd3bfw)(NimStringDesc* name, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg)(NCSTRING* a);
N_LIB_PRIVATE N_NIMCALL(void, getServByPort_UF7NNhoRARWyxcKKRnLExQ)(NU16 port, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, getHostByAddr_am5EZHJJRqP8LgSJZcjXTw)(NimStringDesc* ip, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, getHostByName_4pNvNBdh0QjXDN9aI1Jilqw)(NimStringDesc* name, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getHostname_yWWJQMhb0xdemcFTQgjbcQ)(void);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, getSockDomain_j9cFma7L5fIBlpl9awGYA72A)(int socket);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getAddrString_wIS6MR5PrZV5s3d85jE2nw)(struct sockaddr* sockAddr);
static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem)(NCSTRING x, NCSTRING y);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(NU16, getSockName_VJAFVIID7Gi09bNUDgo9aXuA)(int socket);
N_LIB_PRIVATE N_NIMCALL(void, getLocalAddr_IA9aPOAIFL0HA7Wl9c0gWEEg)(int socket, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, getPeerAddr_IA9aPOAIFL0HA7Wl9c0gWEEg_2)(int socket, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result);
N_LIB_PRIVATE N_NIMCALL(NI, getSockOptInt_7ZeTYMZbCWxCnrevsvDH2g)(int socket, NI level, NI optname);
N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt_AD4OLBf5FHlJkAgq7B9aY5A)(int socket, NI level, NI optname, NI optval);
N_LIB_PRIVATE N_NIMCALL(void, setBlocking_RBApwF6paZ4dy39bsxU85TA)(int s, NIM_BOOL blocking);
N_LIB_PRIVATE N_NIMCALL(struct timeval, timeValFromMilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, createFdSet_2WN0c6XLlKabdgianu73bg)(fd_set* fd, tySequence_9apztJSmgERYU8fZOjI4pOg* s, NI* m);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet_1LwJOFdSmq6EdasZp5EGUA)(tySequence_9apztJSmgERYU8fZOjI4pOg** s, fd_set* fd);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(NI, select_f1UV2yno269c9cyjR0CwiQwg)(tySequence_9apztJSmgERYU8fZOjI4pOg** readfds, NI timeout);
N_LIB_PRIVATE N_NIMCALL(NI, selectRead_f1UV2yno269c9cyjR0CwiQwg_2)(tySequence_9apztJSmgERYU8fZOjI4pOg** readfds, NI timeout);
N_LIB_PRIVATE N_NIMCALL(NI, selectWrite_Mynm9aGCt9cFsRIL52XLwFaw)(tySequence_9apztJSmgERYU8fZOjI4pOg** writefds, NI timeout);
N_LIB_PRIVATE N_NIMCALL(void, accept_nmCCLPlzBoP6AGJgbJepfQ)(int fd, tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ* Result);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
int osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
sa_family_t nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg;
sa_family_t nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_9ak3HAuy7nXhXlidAanTkdQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern TNimType NTI_M4na42GvebBMnI5wV9cYMxg_;
TNimType NTI_azV1qb29cFIFe582aezrNAQ_;
TNimType NTI_Q79bEtFARvq0ekDNtvj3Vqg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_HX2M9cQhE3jaovp9aYJDdslA_;
extern TNimType NTI_9czoZw3pzPyrBmb5zTHY1OQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_J0FzjuY02DFObU1sQZLwJA_;
TNimType NTI_TpwiSlpJ9ammzps6Ja8XpjQ_;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA_;
TNimType NTI_NQT1bItGG2X9byGdrWX7ujw_;
TNimType NTI_dqJ1OqRGclxIMMdSLRzzXg_;
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3, "Service not found.", 18);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8, "unknown h_addrtype", 18);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9, "", 0);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11, "Unknown socket family in getAddrString", 38);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_21, "len(a) == L seq modified while iterating over it", 48);

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(short, toInt_OxnVJkB3zYuSbbBvLQDSVA)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain) {
	short result;
	nimfr_("toInt", "nativesockets.nim");
	result = (short)0;
	nimln_(129, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0):
	{
		nimln_(130, "nativesockets.nim");
		result = ((short)chckRange(AF_UNSPEC, ((short) -32768), ((short) 32767)));
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 1):
	{
		nimln_(131, "nativesockets.nim");
		result = ((short)chckRange(AF_UNIX, ((short) -32768), ((short) 32767)));
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		nimln_(132, "nativesockets.nim");
		result = ((short)chckRange(AF_INET, ((short) -32768), ((short) 32767)));
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30):
	{
		nimln_(133, "nativesockets.nim");
		result = ((short)chckRange(AF_INET6, ((short) -32768), ((short) 32767)));
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ, toKnownDomain_WoQ5UOyB2HAIoN15dknZCw)(int family) {
	tyObject_Option_V9bnQIoRETSshkjE1kDWuNQ result;
	nimfr_("toKnownDomain", "nativesockets.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(138, "nativesockets.nim");
	{
		if (!(family == AF_UNSPEC)) goto LA3_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 0));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(139, "nativesockets.nim");
		if (!(family == AF_UNIX)) goto LA6_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 1));
	}
	goto LA1_;
	LA6_: ;
	{
		nimln_(140, "nativesockets.nim");
		if (!(family == AF_INET)) goto LA9_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2));
	}
	goto LA1_;
	LA9_: ;
	{
		nimln_(141, "nativesockets.nim");
		if (!(family == AF_INET6)) goto LA12_;
		result = some_JMiA9ccATJp8JunIrSlndYA(((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30));
	}
	goto LA1_;
	LA12_: ;
	{
		nimln_(142, "nativesockets.nim");
		result = none_IBO7fiOVpMVOmhrZWFqq1A();
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_0zBaW59cZQJVrz1L13Wid5g)(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw typ) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(145, "nativesockets.nim");
	switch (typ) {
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1):
	{
		nimln_(146, "nativesockets.nim");
		result = SOCK_STREAM;
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 2):
	{
		nimln_(147, "nativesockets.nim");
		result = SOCK_DGRAM;
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 5):
	{
		nimln_(148, "nativesockets.nim");
		result = SOCK_SEQPACKET;
	}
	break;
	case ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 3):
	{
		nimln_(149, "nativesockets.nim");
		result = SOCK_RAW;
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, toInt_slGFLM9cFJ086GOC2tjJphw)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg p) {
	int result;
	nimfr_("toInt", "nativesockets.nim");
	result = (int)0;
	nimln_(152, "nativesockets.nim");
	switch (p) {
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		nimln_(153, "nativesockets.nim");
		result = IPPROTO_TCP;
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		nimln_(154, "nativesockets.nim");
		result = IPPROTO_UDP;
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	{
		nimln_(155, "nativesockets.nim");
		result = IPPROTO_IP;
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	{
		nimln_(156, "nativesockets.nim");
		result = IPPROTO_IPV6;
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	{
		nimln_(157, "nativesockets.nim");
		result = IPPROTO_RAW;
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		nimln_(158, "nativesockets.nim");
		result = IPPROTO_ICMP;
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw, toSockType_zz9bxu9cRa00a9b6j4pehnFgQ)(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw result;
	nimfr_("toSockType", "nativesockets.nim");
	result = (tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw)0;
	nimln_(179, "nativesockets.nim");
	switch (protocol) {
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 6):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 1);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 17):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 2);
	}
	break;
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 18):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 19):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 20):
	case ((tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg) 21):
	{
		result = ((tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw) 3);
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_P59cS8yz3VHsnoN6zylI5Lg)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	int result;
	short T1_;
	int T2_;
	int T3_;
	nimfr_("createNativeSocket", "nativesockets.nim");
	result = (int)0;
	nimln_(190, "nativesockets.nim");
	nimln_(191, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	T2_ = (int)0;
	T2_ = toInt_0zBaW59cZQJVrz1L13Wid5g(sockType);
	T3_ = (int)0;
	T3_ = toInt_slGFLM9cFJ086GOC2tjJphw(protocol);
	result = socket(((int) (T1_)), T2_, T3_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket_xsLKpyGLgUgaTjiALlo5Kw)(int domain, int sockType, int protocol) {
	int result;
	nimfr_("createNativeSocket", "nativesockets.nim");
	result = (int)0;
	nimln_(195, "nativesockets.nim");
	nimln_(199, "nativesockets.nim");
	result = socket(domain, sockType, protocol);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, newNativeSocket_P59cS8yz3VHsnoN6zylI5Lg_2)(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	int result;
	nimfr_("newNativeSocket", "nativesockets.nim");
	result = (int)0;
	nimln_(205, "nativesockets.nim");
	nimln_(208, "nativesockets.nim");
	result = createNativeSocket_P59cS8yz3VHsnoN6zylI5Lg(domain, sockType, protocol);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, newNativeSocket_xsLKpyGLgUgaTjiALlo5Kw_2)(int domain, int sockType, int protocol) {
	int result;
	nimfr_("newNativeSocket", "nativesockets.nim");
	result = (int)0;
	nimln_(213, "nativesockets.nim");
	nimln_(219, "nativesockets.nim");
	result = createNativeSocket_xsLKpyGLgUgaTjiALlo5Kw(domain, sockType, protocol);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, close_ODRNWwddsp7NVetdw9cXCVg)(int socket) {
	int T1_;
	nimfr_("close", "nativesockets.nim");
	nimln_(226, "nativesockets.nim");
	T1_ = (int)0;
	T1_ = close(socket);
	T1_;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(int, bindAddr_zpvqU0KQkzbkoKaehnMX2A)(int socket, struct sockaddr* name, socklen_t namelen) {
	int result;
	nimfr_("bindAddr", "nativesockets.nim");
	result = (int)0;
	nimln_(231, "nativesockets.nim");
	result = bind(socket, name, namelen);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(int, listen_BNAD35QpM7R1C7EJRtAZ3Q)(int socket, int backlog) {
	int result;
	nimfr_("listen", "nativesockets.nim");
	result = (int)0;
	nimln_(240, "nativesockets.nim");
	result = listen(socket, backlog);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo_fNPnGAYqSzdc2OjHEcTTAw)(NimStringDesc* address, NU16 port, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw sockType, tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg protocol) {
	struct addrinfo* result;
	struct addrinfo hints;
	short T1_;
	int gaiResult;
	NimStringDesc* T6_;
	nimfr_("getAddrInfo", "nativesockets.nim");
	result = (struct addrinfo*)0;
	memset((void*)(&hints), 0, sizeof(hints));
	nimln_(249, "nativesockets.nim");
	result = NIM_NIL;
	nimln_(250, "nativesockets.nim");
	T1_ = (short)0;
	T1_ = toInt_OxnVJkB3zYuSbbBvLQDSVA(domain);
	hints.ai_family = ((int) (T1_));
	nimln_(251, "nativesockets.nim");
	hints.ai_socktype = toInt_0zBaW59cZQJVrz1L13Wid5g(sockType);
	nimln_(252, "nativesockets.nim");
	hints.ai_protocol = toInt_slGFLM9cFJ086GOC2tjJphw(protocol);
	nimln_(257, "nativesockets.nim");
	{
		if (!(domain == ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30))) goto LA4_;
		nimln_(258, "nativesockets.nim");
		hints.ai_flags = AI_V4MAPPED;
	}
	LA4_: ;
	nimln_(259, "nativesockets.nim");
	T6_ = (NimStringDesc*)0;
	T6_ = dollar__rzAI8EMyNBAQwGODeohhAA(port);
	gaiResult = getaddrinfo(address->data, T6_->data, (&hints), &result);
	nimln_(260, "nativesockets.nim");
	{
		NI32 T11_;
		NCSTRING T12_;
		NimStringDesc* T13_;
		nimln_(398, "system.nim");
		nimln_(260, "nativesockets.nim");
		if (!!((gaiResult == ((NI32) 0)))) goto LA9_;
		nimln_(264, "nativesockets.nim");
		T11_ = (NI32)0;
		T11_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T12_ = (NCSTRING)0;
		T12_ = (char *)gai_strerror(gaiResult);
		T13_ = (NimStringDesc*)0;
		T13_ = cstrToNimstr(T12_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T11_, T13_);
	}
	LA9_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, dealloc_o4AP9bp2a6Md29bi289aWTZew)(struct addrinfo* ai) {
	nimfr_("dealloc", "nativesockets.nim");
	nimln_(268, "nativesockets.nim");
	freeaddrinfo(ai);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NU32, ntohl_RStKcIp64i7w9c4KBI2z46w)(NU32 x) {
	NU32 result;
	nimfr_("ntohl", "nativesockets.nim");
	result = (NU32)0;
	nimln_(276, "nativesockets.nim");
	nimln_(275, "nativesockets.nim");
	nimln_(276, "nativesockets.nim");
	nimln_(277, "nativesockets.nim");
	nimln_(278, "nativesockets.nim");
	result = (NU32)((NU32)((NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 24))) | (NU32)((NU32)((NU32)(x) >> (NU32)(((NU32) 8))) & ((NU32) 65280))) | (NU32)((NU32)((NU32)(x) << (NU32)(((NU32) 8))) & ((NU32) 16711680))) | (NU32)((NU32)(x) << (NU32)(((NU32) 24))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16, ntohs_hTWZ9cGeQnQNEThS6k8qUKg)(NU16 x) {
	NU16 result;
	nimfr_("ntohs", "nativesockets.nim");
	result = (NU16)0;
	nimln_(294, "nativesockets.nim");
	result = (NU16)((NU16)((NU16)(x) >> (NU16)(((NU16) 8))) | (NU16)((NU16)(x) << (NU16)(((NU16) 8))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, getServByName_NNxs1hil5R9bGsNpctd3bfw)(NimStringDesc* name, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	struct servent* s;
	nimfr_("getServByName", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9ak3HAuy7nXhXlidAanTkdQ_));
	nimln_(344, "nativesockets.nim");
	s = getservbyname(name->data, proto->data);
	nimln_(345, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3));
	}
	LA3_: ;
	nimln_(346, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln_(347, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).s_aliases));
	nimln_(348, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln_(349, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getServByPort_UF7NNhoRARWyxcKKRnLExQ)(NU16 port, NimStringDesc* proto, tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ* Result) {
	struct servent* s;
	nimfr_("getServByPort", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_9ak3HAuy7nXhXlidAanTkdQ_));
	nimln_(360, "nativesockets.nim");
	s = getservbyport(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto->data);
	nimln_(361, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_3));
	}
	LA3_: ;
	nimln_(362, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln_(363, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).s_aliases));
	nimln_(364, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln_(365, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getHostByAddr_am5EZHJJRqP8LgSJZcjXTw)(NimStringDesc* ip, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	struct in_addr myaddr;
	struct hostent* s;
	nimfr_("getHostByAddr", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_azV1qb29cFIFe582aezrNAQ_));
	memset((void*)(&myaddr), 0, sizeof(myaddr));
	nimln_(370, "nativesockets.nim");
	myaddr.s_addr = inet_addr(ip->data);
	nimln_(377, "nativesockets.nim");
	nimln_(382, "nativesockets.nim");
	s = gethostbyaddr(((void*) ((&myaddr))), ((socklen_t) (((NI)sizeof(struct in_addr)))), AF_INET);
	nimln_(384, "nativesockets.nim");
	{
		NI32 T5_;
		NCSTRING T6_;
		NimStringDesc* T7_;
		if (!(s == NIM_NIL)) goto LA3_;
		nimln_(385, "nativesockets.nim");
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		T6_ = (NCSTRING)0;
		T6_ = (char *)hstrerror(h_errno);
		T7_ = (NimStringDesc*)0;
		T7_ = cstrToNimstr(T6_);
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, T7_);
	}
	LA3_: ;
	nimln_(387, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln_(388, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_aliases));
	nimln_(392, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA10_;
		nimln_(393, "nativesockets.nim");
		(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2);
	}
	goto LA8_;
	LA10_: ;
	{
		nimln_(394, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA13_;
		nimln_(395, "nativesockets.nim");
		(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30);
	}
	goto LA8_;
	LA13_: ;
	{
		NI32 T16_;
		nimln_(397, "nativesockets.nim");
		T16_ = (NI32)0;
		T16_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T16_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA8_: ;
	nimln_(398, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrList), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_addr_list));
	nimln_(399, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getHostByName_4pNvNBdh0QjXDN9aI1Jilqw)(NimStringDesc* name, tyObject_Hostent_azV1qb29cFIFe582aezrNAQ* Result) {
	struct hostent* s;
	nimfr_("getHostByName", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_azV1qb29cFIFe582aezrNAQ_));
	nimln_(406, "nativesockets.nim");
	s = gethostbyname(name->data);
	nimln_(407, "nativesockets.nim");
	{
		NI32 T5_;
		if (!(s == NIM_NIL)) goto LA3_;
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3_: ;
	nimln_(408, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln_(409, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_aliases));
	nimln_(413, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA8_;
		nimln_(414, "nativesockets.nim");
		(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2);
	}
	goto LA6_;
	LA8_: ;
	{
		nimln_(415, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA11_;
		nimln_(416, "nativesockets.nim");
		(*Result).addrtype = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30);
	}
	goto LA6_;
	LA11_: ;
	{
		NI32 T14_;
		nimln_(418, "nativesockets.nim");
		T14_ = (NI32)0;
		T14_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T14_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_8));
	}
	LA6_: ;
	nimln_(419, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrList), cstringArrayToSeq_9csDN6Nz9aAfagut7AuPkswg((*s).h_addr_list));
	nimln_(420, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getHostname_yWWJQMhb0xdemcFTQgjbcQ)(void) {
	NimStringDesc* result;
	int success;
	NI x;
	nimfr_("getHostname", "nativesockets.nim");
	result = (NimStringDesc*)0;
	nimln_(427, "nativesockets.nim");
	result = mnewString(((NI) 64));
	nimln_(432, "nativesockets.nim");
	success = gethostname(result->data, ((NI) 64));
	nimln_(433, "nativesockets.nim");
	{
		NI32 T5_;
		nimln_(398, "system.nim");
		nimln_(433, "nativesockets.nim");
		if (!!((success == ((int) 0)))) goto LA3_;
		nimln_(434, "nativesockets.nim");
		T5_ = (NI32)0;
		T5_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T5_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA3_: ;
	nimln_(435, "nativesockets.nim");
	x = (result->data ? strlen(result->data) : 0);
	nimln_(436, "nativesockets.nim");
	result = setLengthStr(result, ((NI)chckRange(x, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg, getSockDomain_j9cFma7L5fIBlpl9awGYA72A)(int socket) {
	tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg result;
	struct sockaddr_in6 name;
	socklen_t namelen;
	nimfr_("getSockDomain", "nativesockets.nim");
	result = (tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg)0;
	memset((void*)(&name), 0, sizeof(name));
	nimln_(441, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
	nimln_(442, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(444, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA4_: ;
	nimln_(445, "nativesockets.nim");
	{
		if (!(name.sin6_family == nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg)) goto LA9_;
		nimln_(446, "nativesockets.nim");
		result = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2);
	}
	goto LA7_;
	LA9_: ;
	{
		nimln_(447, "nativesockets.nim");
		if (!(name.sin6_family == nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA)) goto LA12_;
		nimln_(448, "nativesockets.nim");
		result = ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30);
	}
	goto LA7_;
	LA12_: ;
	{
		NI32 T15_;
		nimln_(450, "nativesockets.nim");
		T15_ = (NI32)0;
		T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_10));
	}
	LA7_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem)(NCSTRING x, NCSTRING y) {
	NIM_BOOL result;
	nimfr_("==", "system.nim");
	result = (NIM_BOOL)0;
	nimln_(4051, "system.nim");
	{
		if (!(((void*) (x)) == ((void*) (y)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
	LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(4052, "system.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = (x == 0);
		if (T6_) goto LA7_;
		T6_ = (y == 0);
		LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
	LA8_: ;
	{
		int T11_;
		nimln_(4053, "system.nim");
		T11_ = (int)0;
		T11_ = strcmp(x, y);
		result = (T11_ == ((NI32) 0));
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, getAddrString_wIS6MR5PrZV5s3d85jE2nw)(struct sockaddr* sockAddr) {
	NimStringDesc* result;
	nimfr_("getAddrString", "nativesockets.nim");
	result = (NimStringDesc*)0;
	nimln_(455, "nativesockets.nim");
	{
		NCSTRING T5_;
		if (!((*sockAddr).sa_family == nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg)) goto LA3_;
		nimln_(456, "nativesockets.nim");
		T5_ = (NCSTRING)0;
		T5_ = inet_ntoa((*((struct sockaddr_in*) (sockAddr))).sin_addr);
		result = cstrToNimstr(T5_);
	}
	goto LA1_;
	LA3_: ;
	{
		int addrLen;
		struct in6_addr* addr6;
		nimln_(457, "nativesockets.nim");
		if (!((*sockAddr).sa_family == nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA)) goto LA7_;
		nimln_(458, "nativesockets.nim");
		addrLen = INET6_ADDRSTRLEN;
		nimln_(460, "nativesockets.nim");
		result = mnewString(((NI)chckRange(addrLen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(461, "nativesockets.nim");
		addr6 = (&(*((struct sockaddr_in6*) (sockAddr))).sin6_addr);
		nimln_(463, "nativesockets.nim");
		{
			NCSTRING T11_;
			NIM_BOOL T12_;
			NI32 T15_;
			if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
			nimln_(464, "nativesockets.nim");
			T11_ = (NCSTRING)0;
			T11_ = (char *)inet_ntop(AF_INET6, ((void*) (addr6)), ((NCSTRING) ((&result->data[((NI) 0)]))), ((NI32)chckRange((result ? result->Sup.len : 0), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			T12_ = (NIM_BOOL)0;
			T12_ = eqeq__9ccNWqrTIE9bcAqE2Q0ro7zgsystem(T11_, NIM_NIL);
			if (!T12_) goto LA13_;
			nimln_(465, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA13_: ;
		nimln_(466, "nativesockets.nim");
		{
			int T18_;
			nimln_(398, "system.nim");
			nimln_(466, "nativesockets.nim");
			T18_ = (int)0;
			T18_ = IN6_IS_ADDR_V4MAPPED(addr6);
			if (!!((T18_ == ((NI32) 0)))) goto LA19_;
			nimln_(467, "nativesockets.nim");
			result = copyStr(result, ((NI) 7));
		}
		LA19_: ;
		nimln_(472, "nativesockets.nim");
		result = setLengthStr(result, ((NI)chckRange((result->data ? strlen(result->data) : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	goto LA1_;
	LA7_: ;
	{
		tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ* e;
		NimStringDesc* T22_;
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ*) newObj((&NTI_HX2M9cQhE3jaovp9aYJDdslA_), sizeof(tyObject_IOError_9czoZw3pzPyrBmb5zTHY1OQ));
		(*e).Sup.Sup.Sup.m_type = (&NTI_9czoZw3pzPyrBmb5zTHY1OQ_);
		nimln_(474, "nativesockets.nim");
		T22_ = (NimStringDesc*)0;
		T22_ = (*e).Sup.Sup.message; (*e).Sup.Sup.message = copyStringRC1(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_11));
		if (T22_) nimGCunrefNoCycle(T22_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(474, "nativesockets.nim");
		raiseException((Exception*)e, "IOError");
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU16, getSockName_VJAFVIID7Gi09bNUDgo9aXuA)(int socket) {
	NU16 result;
	struct sockaddr_in name;
	socklen_t namelen;
	nimfr_("getSockName", "nativesockets.nim");
	result = (NU16)0;
	memset((void*)(&name), 0, sizeof(name));
	nimln_(482, "nativesockets.nim");
	name.sin_family = AF_INET;
	nimln_(485, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln_(486, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(T3_ == ((NI32) -1))) goto LA4_;
		nimln_(488, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA4_: ;
	nimln_(489, "nativesockets.nim");
	result = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, getLocalAddr_IA9aPOAIFL0HA7Wl9c0gWEEg)(int socket, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr_("getLocalAddr", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_J0FzjuY02DFObU1sQZLwJA_));
	nimln_(495, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING T8_;
		memset((void*)(&name), 0, sizeof(name));
		nimln_(501, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln_(502, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln_(503, "nativesockets.nim");
		{
			int T4_;
			NI32 T7_;
			T4_ = (int)0;
			T4_ = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(T4_ == ((NI32) -1))) goto LA5_;
			nimln_(505, "nativesockets.nim");
			T7_ = (NI32)0;
			T7_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T7_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA5_: ;
		nimln_(506, "nativesockets.nim");
		T8_ = (NCSTRING)0;
		T8_ = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(T8_));
		nimln_(507, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30):
	{
		struct sockaddr_in6 name_2;
		socklen_t namelen_2;
		memset((void*)(&name_2), 0, sizeof(name_2));
		nimln_(513, "nativesockets.nim");
		name_2.sin6_family = AF_INET6;
		nimln_(514, "nativesockets.nim");
		namelen_2 = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln_(515, "nativesockets.nim");
		{
			int T12_;
			NI32 T15_;
			T12_ = (int)0;
			T12_ = getsockname(socket, ((struct sockaddr*) ((&name_2))), (&namelen_2));
			if (!(T12_ == ((NI32) -1))) goto LA13_;
			nimln_(517, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA13_: ;
		nimln_(519, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), mnewString(((NI) 64)));
		nimln_(520, "nativesockets.nim");
		{
			NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13;
			NCSTRING T18_;
			NI32 T21_;
			if ((NU)(((NI) 0)) > (NU)((*Result).Field0->Sup.len)) raiseIndexError();
			nimln_(521, "nativesockets.nim");
			TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13 = addInt(((*Result).Field0 ? (*Result).Field0->Sup.len : 0), ((NI) 1));
			T18_ = (NCSTRING)0;
			T18_ = (char *)inet_ntop(name_2.sin6_family, ((void*) ((&name_2.sin6_addr))), ((NCSTRING) ((&(*Result).Field0->data[((NI) 0)]))), ((NI32)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_13), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(T18_ == 0)) goto LA19_;
			nimln_(522, "nativesockets.nim");
			T21_ = (NI32)0;
			T21_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T21_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA19_: ;
		nimln_(523, "nativesockets.nim");
		(*Result).Field0 = setLengthStr((*Result).Field0, ((NI)chckRange(((*Result).Field0->data ? strlen((*Result).Field0->data) : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(524, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name_2.sin6_port);
	}
	break;
	default:
	{
		nimln_(526, "nativesockets.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(((NI32) -1), ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14));
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, getPeerAddr_IA9aPOAIFL0HA7Wl9c0gWEEg_2)(int socket, tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg domain, tyTuple_J0FzjuY02DFObU1sQZLwJA* Result) {
	nimfr_("getPeerAddr", "nativesockets.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_J0FzjuY02DFObU1sQZLwJA_));
	nimln_(532, "nativesockets.nim");
	switch (domain) {
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING T8_;
		memset((void*)(&name), 0, sizeof(name));
		nimln_(538, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln_(539, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln_(540, "nativesockets.nim");
		{
			int T4_;
			NI32 T7_;
			T4_ = (int)0;
			T4_ = getpeername(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(T4_ == ((NI32) -1))) goto LA5_;
			nimln_(542, "nativesockets.nim");
			T7_ = (NI32)0;
			T7_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T7_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA5_: ;
		nimln_(543, "nativesockets.nim");
		T8_ = (NCSTRING)0;
		T8_ = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(T8_));
		nimln_(544, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name.sin_port);
	}
	break;
	case ((tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg) 30):
	{
		struct sockaddr_in6 name_2;
		socklen_t namelen_2;
		memset((void*)(&name_2), 0, sizeof(name_2));
		nimln_(550, "nativesockets.nim");
		name_2.sin6_family = AF_INET6;
		nimln_(551, "nativesockets.nim");
		namelen_2 = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln_(552, "nativesockets.nim");
		{
			int T12_;
			NI32 T15_;
			T12_ = (int)0;
			T12_ = getpeername(socket, ((struct sockaddr*) ((&name_2))), (&namelen_2));
			if (!(T12_ == ((NI32) -1))) goto LA13_;
			nimln_(554, "nativesockets.nim");
			T15_ = (NI32)0;
			T15_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T15_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA13_: ;
		nimln_(556, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), mnewString(((NI) 64)));
		nimln_(557, "nativesockets.nim");
		{
			NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15;
			NCSTRING T18_;
			NI32 T21_;
			if ((NU)(((NI) 0)) > (NU)((*Result).Field0->Sup.len)) raiseIndexError();
			nimln_(558, "nativesockets.nim");
			TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15 = addInt(((*Result).Field0 ? (*Result).Field0->Sup.len : 0), ((NI) 1));
			T18_ = (NCSTRING)0;
			T18_ = (char *)inet_ntop(name_2.sin6_family, ((void*) ((&name_2.sin6_addr))), ((NCSTRING) ((&(*Result).Field0->data[((NI) 0)]))), ((NI32)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_15), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!(T18_ == 0)) goto LA19_;
			nimln_(559, "nativesockets.nim");
			T21_ = (NI32)0;
			T21_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T21_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA19_: ;
		nimln_(560, "nativesockets.nim");
		(*Result).Field0 = setLengthStr((*Result).Field0, ((NI)chckRange(((*Result).Field0->data ? strlen((*Result).Field0->data) : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln_(561, "nativesockets.nim");
		(*Result).Field1 = ntohs_hTWZ9cGeQnQNEThS6k8qUKg(name_2.sin6_port);
	}
	break;
	default:
	{
		nimln_(563, "nativesockets.nim");
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(((NI32) -1), ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_14));
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, getSockOptInt_7ZeTYMZbCWxCnrevsvDH2g)(int socket, NI level, NI optname) {
	NI result;
	int res;
	socklen_t size;
	nimfr_("getSockOptInt", "nativesockets.nim");
	result = (NI)0;
	res = (int)0;
	nimln_(569, "nativesockets.nim");
	size = ((socklen_t) 4);
	nimln_(570, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = getsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res))), (&size));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		nimln_(572, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA4_: ;
	nimln_(573, "nativesockets.nim");
	result = ((NI) (res));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt_AD4OLBf5FHlJkAgq7B9aY5A)(int socket, NI level, NI optname, NI optval) {
	int value;
	nimfr_("setSockOptInt", "nativesockets.nim");
	nimln_(578, "nativesockets.nim");
	value = ((int)chckRange(optval, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln_(579, "nativesockets.nim");
	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = setsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value))), ((socklen_t) 4));
		if (!(T3_ < ((NI32) 0))) goto LA4_;
		nimln_(581, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	LA4_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, setBlocking_RBApwF6paZ4dy39bsxU85TA)(int s, NIM_BOOL blocking) {
	NI x;
	int T1_;
	nimfr_("setBlocking", "nativesockets.nim");
	nimln_(592, "nativesockets.nim");
	T1_ = (int)0;
	T1_ = fcntl(s, F_GETFL, ((NI) 0));
	x = ((NI) (T1_));
	nimln_(593, "nativesockets.nim");
	{
		NI32 T6_;
		if (!(x == ((NI) -1))) goto LA4_;
		nimln_(594, "nativesockets.nim");
		T6_ = (NI32)0;
		T6_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
		raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T6_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
	}
	goto LA2_;
	LA4_: ;
	{
		NI mode;
		nimln_(596, "nativesockets.nim");
		{
			if (!blocking) goto LA10_;
			mode = (NI)(x & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
		}
		goto LA8_;
		LA10_: ;
		{
			mode = (NI)(x | ((NI) (O_NONBLOCK)));
		}
		LA8_: ;
		nimln_(597, "nativesockets.nim");
		{
			int T15_;
			NI32 T18_;
			T15_ = (int)0;
			T15_ = fcntl(s, F_SETFL, mode);
			if (!(T15_ == ((NI32) -1))) goto LA16_;
			nimln_(598, "nativesockets.nim");
			T18_ = (NI32)0;
			T18_ = osLastError_tNPXXFl9cb3BG0pJKzUn9bew();
			raiseOSError_bEwAamo1N7TKcaU9akpiyIg(T18_, ((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9));
		}
		LA16_: ;
	}
	LA2_: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(struct timeval, timeValFromMilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ)(NI timeout) {
	struct timeval result;
	nimfr_("timeValFromMilliseconds", "nativesockets.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(601, "nativesockets.nim");
	{
		NI seconds;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_18;
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19;
		nimln_(398, "system.nim");
		nimln_(601, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(602, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16 = divInt(timeout, ((NI) 1000));
		seconds = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_16);
		nimln_(603, "nativesockets.nim");
		result.tv_sec = ((NI) (((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln_(604, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17 = mulInt(seconds, ((NI) 1000));
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_18 = subInt(timeout, (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_17));
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19 = mulInt((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_18), ((NI) 1000));
		result.tv_usec = ((NI) (((NI32)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_19), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, createFdSet_2WN0c6XLlKabdgianu73bg)(fd_set* fd, tySequence_9apztJSmgERYU8fZOjI4pOg* s, NI* m) {
	nimfr_("createFdSet", "nativesockets.nim");
	nimln_(607, "nativesockets.nim");
	FD_ZERO(fd);
	{
		int i;
		NI i_2;
		NI L;
		NI T2_;
		i = (int)0;
		nimln_(3805, "system.nim");
		i_2 = ((NI) 0);
		nimln_(3806, "system.nim");
		T2_ = (s ? s->Sup.len : 0);
		L = T2_;
		{
			nimln_(3807, "system.nim");
			while (1) {
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20;
				if (!(i_2 < L)) goto LA4;
				nimln_(3808, "system.nim");
				if ((NU)(i_2) >= (NU)(s->Sup.len)) raiseIndexError();
				i = s->data[i_2];
				nimln_(609, "nativesockets.nim");
				(*m) = (((*m) >= ((NI) (i))) ? (*m) : ((NI) (i)));
				nimln_(610, "nativesockets.nim");
				FD_SET(i, fd);
				nimln_(3809, "system.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_20);
				nimln_(3810, "system.nim");
				{
					NI T7_;
					T7_ = (s ? s->Sup.len : 0);
					if (!!((T7_ == L))) goto LA8_;
					failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_21));
				}
				LA8_: ;
			} LA4: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pruneSocketSet_1LwJOFdSmq6EdasZp5EGUA)(tySequence_9apztJSmgERYU8fZOjI4pOg** s, fd_set* fd) {
	NI i;
	NI L;
	NI T1_;
	nimfr_("pruneSocketSet", "nativesockets.nim");
	nimln_(613, "nativesockets.nim");
	i = ((NI) 0);
	nimln_(614, "nativesockets.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	L = T1_;
	{
		nimln_(615, "nativesockets.nim");
		while (1) {
			if (!(i < L)) goto LA3;
			nimln_(616, "nativesockets.nim");
			{
				int T6_;
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22;
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				T6_ = (int)0;
				T6_ = FD_ISSET((*s)->data[i], fd);
				if (!(T6_ == ((NI32) 0))) goto LA7_;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				nimln_(617, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				(*s)->data[i] = (*s)->data[(NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_22)];
				nimln_(618, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23 = subInt(L, ((NI) 1));
				L = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_23);
			}
			goto LA4_;
			LA7_: ;
			{
				NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24;
				nimln_(620, "nativesockets.nim");
				TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24 = addInt(i, ((NI) 1));
				i = (NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_24);
			}
			LA4_: ;
		} LA3: ;
	}
	nimln_(621, "nativesockets.nim");
	(*s) = (tySequence_9apztJSmgERYU8fZOjI4pOg*) setLengthSeq(&((*s))->Sup, sizeof(int), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, select_f1UV2yno269c9cyjR0CwiQwg)(tySequence_9apztJSmgERYU8fZOjI4pOg** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set rd;
	NI m;
	nimfr_("select", "nativesockets.nim");
	result = (NI)0;
	nimln_(633, "nativesockets.nim");
	tv = timeValFromMilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln_(636, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(637, "nativesockets.nim");
	createFdSet_2WN0c6XLlKabdgianu73bg((&rd), (*readfds), (&m));
	nimln_(639, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25;
		int T5_;
		nimln_(398, "system.nim");
		nimln_(639, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(640, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_25), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26;
		int T7_;
		nimln_(642, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_26), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(644, "nativesockets.nim");
	pruneSocketSet_1LwJOFdSmq6EdasZp5EGUA(readfds, (&rd));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, selectRead_f1UV2yno269c9cyjR0CwiQwg_2)(tySequence_9apztJSmgERYU8fZOjI4pOg** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set rd;
	NI m;
	nimfr_("selectRead", "nativesockets.nim");
	result = (NI)0;
	nimln_(654, "nativesockets.nim");
	tv = timeValFromMilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln_(657, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(658, "nativesockets.nim");
	createFdSet_2WN0c6XLlKabdgianu73bg((&rd), (*readfds), (&m));
	nimln_(660, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27;
		int T5_;
		nimln_(398, "system.nim");
		nimln_(660, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(661, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_27), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28;
		int T7_;
		nimln_(663, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_28), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(665, "nativesockets.nim");
	pruneSocketSet_1LwJOFdSmq6EdasZp5EGUA(readfds, (&rd));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, selectWrite_Mynm9aGCt9cFsRIL52XLwFaw)(tySequence_9apztJSmgERYU8fZOjI4pOg** writefds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set wr;
	NI m;
	nimfr_("selectWrite", "nativesockets.nim");
	result = (NI)0;
	nimln_(676, "nativesockets.nim");
	tv = timeValFromMilliseconds_X7JbWdPaNDQPHMVB9aPz9bkQ(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln_(679, "nativesockets.nim");
	m = ((NI) 0);
	nimln_(680, "nativesockets.nim");
	createFdSet_2WN0c6XLlKabdgianu73bg((&wr), (*writefds), (&m));
	nimln_(682, "nativesockets.nim");
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_29;
		int T5_;
		nimln_(398, "system.nim");
		nimln_(682, "nativesockets.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3_;
		nimln_(683, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_29 = addInt(m, ((NI) 1));
		T5_ = (int)0;
		T5_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_29), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (T5_));
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30;
		int T7_;
		nimln_(685, "nativesockets.nim");
		TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30 = addInt(m, ((NI) 1));
		T7_ = (int)0;
		T7_ = select(((int)chckRange((NI)(TM_f9bP3LqjpgpB9cXL8Nnak7tQ_30), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (T7_));
	}
	LA1_: ;
	nimln_(687, "nativesockets.nim");
	pruneSocketSet_1LwJOFdSmq6EdasZp5EGUA(writefds, (&wr));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, accept_nmCCLPlzBoP6AGJgbJepfQ)(int fd, tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ* Result) {
	struct sockaddr_in sockAddress;
	socklen_t addrLen;
	int sock;
	nimfr_("accept", "nativesockets.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_TpwiSlpJ9ammzps6Ja8XpjQ_));
	memset((void*)(&sockAddress), 0, sizeof(sockAddress));
	nimln_(694, "nativesockets.nim");
	addrLen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln_(695, "nativesockets.nim");
	sock = accept(fd, ((struct sockaddr*) ((&sockAddress))), (&addrLen));
	nimln_(697, "nativesockets.nim");
	{
		if (!(sock == osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w)) goto LA3_;
		nimln_(698, "nativesockets.nim");
		(*Result).Field0 = osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w;
		unsureAsgnRef((void**) (&(*Result).Field1), copyString(((NimStringDesc*) &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_9)));
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		NCSTRING T6_;
		nimln_(700, "nativesockets.nim");
		(*Result).Field0 = sock;
		T6_ = (NCSTRING)0;
		T6_ = inet_ntoa(sockAddress.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field1), cstrToNimstr(T6_));
		goto BeforeRet_;
	}
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr_("nativesockets", "nativesockets.nim");
	nimln_(108, "nativesockets.nim");
	osInvalidSocket_voz9aUXu8jtRbvGZZJHNE8w = ((int) -1);
	nimln_(109, "nativesockets.nim");
	nativeAfInet_rQwsjQjVqXvdaL9aZofzWwg = AF_INET;
	nimln_(110, "nativesockets.nim");
	nativeAfInet6_Da6PongZL9aJxBrf7qeBmfA = AF_INET6;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[4];
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[5];
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[4] = {
"AF_UNSPEC", 
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[2];
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[2];
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_32[4];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TM_f9bP3LqjpgpB9cXL8Nnak7tQ_35[6];
NI TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37;
static char* NIM_CONST TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[34];
NTI_9ak3HAuy7nXhXlidAanTkdQ_.size = sizeof(tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ);
NTI_9ak3HAuy7nXhXlidAanTkdQ_.kind = 18;
NTI_9ak3HAuy7nXhXlidAanTkdQ_.base = 0;
NTI_9ak3HAuy7nXhXlidAanTkdQ_.flags = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[0] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].offset = offsetof(tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ, name);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[1].name = "name";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[1] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].offset = offsetof(tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ, aliases);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[2].name = "aliases";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[2] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].offset = offsetof(tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ, port);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[3].name = "port";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[3] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].offset = offsetof(tyObject_Servent_9ak3HAuy7nXhXlidAanTkdQ, proto);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[4].name = "proto";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_2[0];
NTI_9ak3HAuy7nXhXlidAanTkdQ_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[0];
NTI_azV1qb29cFIFe582aezrNAQ_.size = sizeof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ);
NTI_azV1qb29cFIFe582aezrNAQ_.kind = 18;
NTI_azV1qb29cFIFe582aezrNAQ_.base = 0;
NTI_azV1qb29cFIFe582aezrNAQ_.flags = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[0] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].offset = offsetof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ, name);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[6].name = "name";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[1] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].offset = offsetof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ, aliases);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[7].name = "aliases";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[2] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.size = sizeof(tyEnum_Domain_Q79bEtFARvq0ekDNtvj3Vqg);
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.kind = 14;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.base = 0;
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+9].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+9].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+9].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_6[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_7+9];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[9].offset = 0;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[10].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[11].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[12].offset = 30;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_5[0];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[13];
NTI_Q79bEtFARvq0ekDNtvj3Vqg_.flags = 1<<2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].offset = offsetof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ, addrtype);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].typ = (&NTI_Q79bEtFARvq0ekDNtvj3Vqg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[8].name = "addrtype";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[3] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].offset = offsetof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ, length);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[14].name = "length";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[4] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].offset = offsetof(tyObject_Hostent_azV1qb29cFIFe582aezrNAQ, addrList);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].typ = (&NTI_sM4lkSb7zS6F7OVMvW9cffQ_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[15].name = "addrList";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].len = 5; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_4[0];
NTI_azV1qb29cFIFe582aezrNAQ_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[5];
NTI_J0FzjuY02DFObU1sQZLwJA_.size = sizeof(tyTuple_J0FzjuY02DFObU1sQZLwJA);
NTI_J0FzjuY02DFObU1sQZLwJA_.kind = 18;
NTI_J0FzjuY02DFObU1sQZLwJA_.base = 0;
NTI_J0FzjuY02DFObU1sQZLwJA_.flags = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[0] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].offset = offsetof(tyTuple_J0FzjuY02DFObU1sQZLwJA, Field0);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[17].name = "Field0";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[1] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].offset = offsetof(tyTuple_J0FzjuY02DFObU1sQZLwJA, Field1);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[18].name = "Field1";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].len = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_12[0];
NTI_J0FzjuY02DFObU1sQZLwJA_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[16];
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.size = sizeof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ);
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.kind = 18;
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.base = 0;
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.flags = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[0] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20].offset = offsetof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ, Field0);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20].typ = (&NTI_nlCscttRCss70IBTyuBqnA_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[20].name = "Field0";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[1] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[21];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[21].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[21].offset = offsetof(tyTuple_TpwiSlpJ9ammzps6Ja8XpjQ, Field1);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[21].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[21].name = "Field1";
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].len = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_31[0];
NTI_TpwiSlpJ9ammzps6Ja8XpjQ_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[19];
NTI_NQT1bItGG2X9byGdrWX7ujw_.size = sizeof(tyEnum_SockType_NQT1bItGG2X9byGdrWX7ujw);
NTI_NQT1bItGG2X9byGdrWX7ujw_.kind = 14;
NTI_NQT1bItGG2X9byGdrWX7ujw_.base = 0;
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34 < 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34+22].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34+22].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34+22].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_33[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_32[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_34+22];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[22].offset = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[23].offset = 2;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[24].offset = 3;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[25].offset = 5;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[26].len = 4; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[26].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[26].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_32[0];
NTI_NQT1bItGG2X9byGdrWX7ujw_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[26];
NTI_NQT1bItGG2X9byGdrWX7ujw_.flags = 1<<2;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.size = sizeof(tyEnum_Protocol_dqJ1OqRGclxIMMdSLRzzXg);
NTI_dqJ1OqRGclxIMMdSLRzzXg_.kind = 14;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.base = 0;
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 3;
for (TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37 = 0; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37 < 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37++) {
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37+27].kind = 1;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37+27].offset = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37+27].name = TM_f9bP3LqjpgpB9cXL8Nnak7tQ_36[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37];
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_35[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37] = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[TM_f9bP3LqjpgpB9cXL8Nnak7tQ_37+27];
}
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[27].offset = 6;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[28].offset = 17;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[29].offset = 18;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[30].offset = 19;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[31].offset = 20;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[32].offset = 21;
TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[33].len = 6; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[33].kind = 2; TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[33].sons = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_35[0];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.node = &TM_f9bP3LqjpgpB9cXL8Nnak7tQ_0[33];
NTI_dqJ1OqRGclxIMMdSLRzzXg_.flags = 1<<2;
}

