/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_uri.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_uri.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ {
NimStringDesc* scheme;
NimStringDesc* username;
NimStringDesc* password;
NimStringDesc* hostname;
NimStringDesc* port;
NimStringDesc* path;
NimStringDesc* query;
NimStringDesc* anchor;
NIM_BOOL opaque;
};
typedef NU8 tySet_tyChar_nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef NU8 tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ;
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__CtKWjB7Zz81HP54gZpd0kQ)(NimStringDesc* url);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__NzjwtZJjJCi2VC4SJCsAJg)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add_8x8SAuzyINKkEnS9cUhjtig)(NimStringDesc** url, NimStringDesc* a);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeUrl_H9bjIhbPEDIqP3g9cmua3TpQ)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x, NI len);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeUrl_H9bjIhbPEDIqP3g9cmua3TpQ_2)(NimStringDesc* s);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
static N_INLINE(void, handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri)(NIM_CHAR c, NI* x);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_LIB_PRIVATE N_NIMCALL(void, parseAuthority_MuG6s2bAvx9cZweCqxUbCdw)(NimStringDesc* authority, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result);
N_LIB_PRIVATE N_NIMCALL(void, parsePath_Kk9czUCtpspxIGySYVuPs9bQ)(NimStringDesc* uri, NI* i, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result);
static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a, NimStringDesc* b);
N_LIB_PRIVATE N_NIMCALL(void, initUri_KjX0htiF0llidA9bDLRUx0g)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(void, resetUri_p9buM2dTitsqXTMz6vOVUyQ)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri);
N_LIB_PRIVATE N_NIMCALL(void, parseUri_rSbDZf9caa6pIyn5lw5aylw)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result);
static N_INLINE(NI, parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw validChars, NI start);
N_LIB_PRIVATE N_NIMCALL(void, parseUri_HN0Rsm1KKAfXov53XGF88Q)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ)(NimStringDesc* path);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s);
static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen);
static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old);
N_LIB_PRIVATE N_NIMCALL(void*, growObj_AVYny8c0GTk28gxjmat1MA)(void* old, NI newsize);
N_NIMCALL(TNimType*, extGetCellType)(void* c);
N_LIB_PRIVATE N_NIMCALL(void, forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA)(void* dest, TNimType* mt, tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ op);
static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, merge_18P4yVuuwO3AQV9a7ftFwqA)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* base, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* reference);
static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NI, rfind_GYN9aIPE4YImn9c3fuLInlTg)(NimStringDesc* s, NimStringDesc* sub, NI start);
static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(void, combine_VvDeUAddaSa6f9c4L9bbifew)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* base, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* reference, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuStartsWith)(NimStringDesc* s, NimStringDesc* prefix);
N_LIB_PRIVATE N_NIMCALL(void, combine_t58oLEw9ciSu2pjqeOck9azg)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uris, NI urisLen_0, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
N_NIMCALL(void, genericShallowAssign)(void* dest, void* src, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAbsolute_qN9cts56Np81Y0BUTVYLZ4A)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri);
N_LIB_PRIVATE N_NIMCALL(void, slash__zM0XqLEoeXfdWrrSUdJ9c4g)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* x, NimStringDesc* path, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Q6hX9cwycP8fRn52OpcLEjw)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* u);
static N_INLINE(NIM_BOOL, endsWith_znzByIhLc10EfS4jWWkP2wuri)(NimStringDesc* s, NIM_CHAR suffix);
static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQuri)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_j49bukNPrq747O1GRd4Ng9bQ_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_11, "false ", 6);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_21 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_23, "mailto", 6);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_25 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_28 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_31, "", 0);
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_35 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x68, 0xFF, 0x03,
0xFE, 0xFF, 0xFF, 0x07, 0xFE, 0xFF, 0xFF, 0x07,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
static NIM_CONST tySet_tyChar_nmiMWKVIe46vacnhAFrQvw TM_VzbRQH9cb1xm1tSKH4PwBSw_40 = {
0x00, 0x00, 0x00, 0x00, 0x08, 0x80, 0x00, 0x80,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}
;
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_50, "/", 1);
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_58, ":", 1);
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_59, "://", 3);
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_60, "@", 1);
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_66, "\?", 1);
STRING_LITERAL(TM_VzbRQH9cb1xm1tSKH4PwBSw_67, "#", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__CtKWjB7Zz81HP54gZpd0kQ)(NimStringDesc* url) {
	NimStringDesc* result;
	nimfr_("$", "uri.nim");
{	result = (NimStringDesc*)0;
	nimln_(26, "uri.nim");
	result = copyString(url);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__NzjwtZJjJCi2VC4SJCsAJg)(NimStringDesc* a, NimStringDesc* b) {
	NimStringDesc* result;
	NimStringDesc* urlS;
	NimStringDesc* bS;
	nimfr_("/", "uri.nim");
{	result = (NimStringDesc*)0;
	nimln_(32, "uri.nim");
	urlS = dollar__CtKWjB7Zz81HP54gZpd0kQ(a);
	nimln_(33, "uri.nim");
	bS = dollar__CtKWjB7Zz81HP54gZpd0kQ(b);
	nimln_(34, "uri.nim");
	{
		if (!((urlS) && (urlS)->Sup.len == 0)) goto LA3_;
		result = copyString(b);
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(35, "uri.nim");
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_2;
		nimln_(398, "system.nim");
		nimln_(35, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_2 = subInt((urlS ? urlS->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_2)) > (NU)(urlS->Sup.len)) raiseIndexError();
		if (!!(((NU8)(urlS->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_2)]) == (NU8)(47)))) goto LA7_;
		nimln_(36, "uri.nim");
		urlS = addChar(urlS, 47);
	}
	LA7_: ;
	nimln_(37, "uri.nim");
	{
		NimStringDesc* T13_;
		if ((NU)(((NI) 0)) > (NU)(bS->Sup.len)) raiseIndexError();
		if (!((NU8)(bS->data[((NI) 0)]) == (NU8)(47))) goto LA11_;
		nimln_(38, "uri.nim");
		T13_ = (NimStringDesc*)0;
		T13_ = copyStr(bS, ((NI) 1));
		urlS = resizeString(urlS, T13_->Sup.len + 0);
appendString(urlS, T13_);
	}
	goto LA9_;
	LA11_: ;
	{
		nimln_(40, "uri.nim");
		urlS = resizeString(urlS, bS->Sup.len + 0);
appendString(urlS, bS);
	}
	LA9_: ;
	nimln_(41, "uri.nim");
	result = copyString(urlS);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, add_8x8SAuzyINKkEnS9cUhjtig)(NimStringDesc** url, NimStringDesc* a) {
	nimfr_("add", "uri.nim");
	nimln_(47, "uri.nim");
	unsureAsgnRef((void**) (&(*url)), slash__NzjwtZJjJCi2VC4SJCsAJg((*url), a));
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, encodeUrl_H9bjIhbPEDIqP3g9cmua3TpQ)(NimStringDesc* s) {
	NimStringDesc* result;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_3;
	nimfr_("encodeUrl", "uri.nim");
	result = (NimStringDesc*)0;
	nimln_(55, "uri.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_3 = addInt((s ? s->Sup.len : 0), (NI)((NU64)((s ? s->Sup.len : 0)) >> (NU64)(((NI) 2))));
	result = rawNewString(((NI)chckRange((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_3), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI colontmp_;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_4;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(56, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_4 = subInt((s ? s->Sup.len : 0), ((NI) 1));
		colontmp_ = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_4);
		nimln_(2045, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2046, "system.nim");
			while (1) {
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_5;
				if (!(res <= colontmp_)) goto LA3;
				nimln_(2047, "system.nim");
				i = res;
				nimln_(57, "uri.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				switch (((NU8)(s->data[i]))) {
				case 97 ... 122:
				case 65 ... 90:
				case 48 ... 57:
				case 95:
				{
					nimln_(58, "uri.nim");
					if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
					result = addChar(result, s->data[i]);
				}
				break;
				case 32:
				{
					nimln_(59, "uri.nim");
					result = addChar(result, 43);
				}
				break;
				default:
				{
					NimStringDesc* T7_;
					nimln_(61, "uri.nim");
					result = addChar(result, 37);
					nimln_(62, "uri.nim");
					if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
					T7_ = (NimStringDesc*)0;
					T7_ = nsuToHex(((NI64) (((NU8)(s->data[i])))), ((NI) 2));
					result = resizeString(result, T7_->Sup.len + 0);
appendString(result, T7_);
				}
				break;
				}
				nimln_(2048, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_5 = addInt(res, ((NI) 1));
				res = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(void, handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri)(NIM_CHAR c, NI* x) {
	nimfr_("handleHexChar", "uri.nim");
	nimln_(70, "uri.nim");
	switch (((NU8)(c))) {
	case 48 ... 57:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_6;
		nimln_(71, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_6 = subInt(((NU8)(c)), ((NI) 48));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_6));
	}
	break;
	case 97 ... 102:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_7;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_8;
		nimln_(72, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_7 = subInt(((NU8)(c)), ((NI) 97));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_8 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_7), ((NI) 10));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_8));
	}
	break;
	case 65 ... 70:
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_9;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_10;
		nimln_(73, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_9 = subInt(((NU8)(c)), ((NI) 65));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_10 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_9), ((NI) 10));
		(*x) = (NI)((NI)((NU64)((*x)) << (NU64)(((NI) 4))) | (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_10));
	}
	break;
	default:
	{
		nimln_(74, "uri.nim");
		{
			if (!NIM_TRUE) goto LA7_;
			failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_11));
		}
		LA7_: ;
	}
	break;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, decodeUrl_H9bjIhbPEDIqP3g9cmua3TpQ_2)(NimStringDesc* s) {
	NimStringDesc* result;
	NI i;
	NI j;
	nimfr_("decodeUrl", "uri.nim");
	result = (NimStringDesc*)0;
	nimln_(76, "uri.nim");
	result = mnewString(((NI)chckRange((s ? s->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(77, "uri.nim");
	i = ((NI) 0);
	nimln_(78, "uri.nim");
	j = ((NI) 0);
	{
		nimln_(79, "uri.nim");
		while (1) {
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_15;
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_16;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(80, "uri.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			switch (((NU8)(s->data[i]))) {
			case 37:
			{
				NI x;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_12;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_13;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_14;
				nimln_(82, "uri.nim");
				x = ((NI) 0);
				nimln_(83, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_12 = addInt(i, ((NI) 1));
				if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_12)) > (NU)(s->Sup.len)) raiseIndexError();
				handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri(s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_12)], (&x));
				nimln_(84, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_13 = addInt(i, ((NI) 2));
				if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_13)) > (NU)(s->Sup.len)) raiseIndexError();
				handleHexChar_g0Mc9bquhMvGhJuSAXY34qguri(s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_13)], (&x));
				nimln_(85, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_14 = addInt(i, ((NI) 2));
				i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_14);
				if ((NU)(j) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(86, "uri.nim");
				result->data[j] = ((NIM_CHAR) (((NI)chckRange(x, ((NI) 0), ((NI) 255)))));
			}
			break;
			case 43:
			{
				if ((NU)(j) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(87, "uri.nim");
				result->data[j] = 32;
			}
			break;
			default:
			{
				if ((NU)(j) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(88, "uri.nim");
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[j] = s->data[i];
			}
			break;
			}
			nimln_(89, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_15 = addInt(i, ((NI) 1));
			i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_15);
			nimln_(90, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_16 = addInt(j, ((NI) 1));
			j = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_16);
		} LA2: ;
	}
	nimln_(91, "uri.nim");
	result = setLengthStr(result, ((NI)chckRange(j, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseAuthority_MuG6s2bAvx9cZweCqxUbCdw)(NimStringDesc* authority, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI i;
	NIM_BOOL inPort;
	NIM_BOOL inIPv6;
	nimfr_("parseAuthority", "uri.nim");
	nimln_(94, "uri.nim");
	i = ((NI) 0);
	nimln_(95, "uri.nim");
	inPort = NIM_FALSE;
	nimln_(96, "uri.nim");
	inIPv6 = NIM_FALSE;
	{
		nimln_(97, "uri.nim");
		while (1) {
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_17;
			nimln_(98, "uri.nim");
			if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
			switch (((NU8)(authority->data[i]))) {
			case 64:
			{
				NimStringDesc* T4_;
				NimStringDesc* T5_;
				nimln_(100, "uri.nim");
				T4_ = (NimStringDesc*)0;
				T4_ = (*result).password;
				unsureAsgnRef((void**) (&(*result).password), (*result).port);
				unsureAsgnRef((void**) (&(*result).port), T4_);
				nimln_(101, "uri.nim");
				(*result).port = setLengthStr((*result).port, ((NI) 0));
				nimln_(102, "uri.nim");
				T5_ = (NimStringDesc*)0;
				T5_ = (*result).username;
				unsureAsgnRef((void**) (&(*result).username), (*result).hostname);
				unsureAsgnRef((void**) (&(*result).hostname), T5_);
				nimln_(103, "uri.nim");
				(*result).hostname = setLengthStr((*result).hostname, ((NI) 0));
				nimln_(104, "uri.nim");
				inPort = NIM_FALSE;
			}
			break;
			case 58:
			{
				nimln_(106, "uri.nim");
				{
					if (!inIPv6) goto LA9_;
					nimln_(107, "uri.nim");
					if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
					(*result).hostname = addChar((*result).hostname, authority->data[i]);
				}
				goto LA7_;
				LA9_: ;
				{
					nimln_(109, "uri.nim");
					inPort = NIM_TRUE;
				}
				LA7_: ;
			}
			break;
			case 91:
			{
				nimln_(111, "uri.nim");
				inIPv6 = NIM_TRUE;
			}
			break;
			case 93:
			{
				nimln_(113, "uri.nim");
				inIPv6 = NIM_FALSE;
			}
			break;
			case 0:
			{
				nimln_(114, "uri.nim");
				goto LA1;
			}
			break;
			default:
			{
				nimln_(116, "uri.nim");
				{
					if (!inPort) goto LA18_;
					nimln_(117, "uri.nim");
					if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
					(*result).port = addChar((*result).port, authority->data[i]);
				}
				goto LA16_;
				LA18_: ;
				{
					nimln_(119, "uri.nim");
					if ((NU)(i) > (NU)(authority->Sup.len)) raiseIndexError();
					(*result).hostname = addChar((*result).hostname, authority->data[i]);
				}
				LA16_: ;
			}
			break;
			}
			nimln_(120, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_17 = addInt(i, ((NI) 1));
			i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_17);
		}
	} LA1: ;
	popFrame();
}

static N_INLINE(NI, parseUntil_zSglkPmqQkVaLkVSiDuiCguri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw until, NI start) {
	NI result;
	NI i;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_19;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_20;
	nimfr_("parseUntil", "parseutils.nim");
	result = (NI)0;
	nimln_(180, "parseutils.nim");
	i = start;
	{
		nimln_(181, "parseutils.nim");
		while (1) {
			NIM_BOOL T3_;
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_18;
			T3_ = (NIM_BOOL)0;
			T3_ = (i < (s ? s->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			nimln_(1212, "system.nim");
			nimln_(181, "parseutils.nim");
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			T3_ = !(((until[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0));
			LA4_: ;
			if (!T3_) goto LA2;
			TM_VzbRQH9cb1xm1tSKH4PwBSw_18 = addInt(i, ((NI) 1));
			i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_18);
		} LA2: ;
	}
	nimln_(182, "parseutils.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_19 = subInt(i, start);
	result = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_19);
	nimln_(183, "parseutils.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_20 = subInt(i, ((NI) 1));
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_20)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parsePath_Kk9czUCtpspxIGySYVuPs9bQ)(NimStringDesc* uri, NI* i, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI T1_;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_22;
	nimfr_("parsePath", "uri.nim");
	nimln_(124, "uri.nim");
	T1_ = (NI)0;
	T1_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).path), TM_VzbRQH9cb1xm1tSKH4PwBSw_21, (*i));
	TM_VzbRQH9cb1xm1tSKH4PwBSw_22 = addInt((*i), T1_);
	(*i) = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_22);
	nimln_(127, "uri.nim");
	{
		NI T4_;
		T4_ = (NI)0;
		T4_ = nsuCmpIgnoreCase((*result).scheme, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_23));
		if (!(T4_ == ((NI) 0))) goto LA5_;
		nimln_(128, "uri.nim");
		parseAuthority_MuG6s2bAvx9cZweCqxUbCdw((*result).path, result);
		nimln_(129, "uri.nim");
		(*result).path = setLengthStr((*result).path, ((NI) 0));
	}
	LA5_: ;
	nimln_(131, "uri.nim");
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_24;
		NI T11_;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_26;
		if ((NU)((*i)) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[(*i)]) == (NU8)(63))) goto LA9_;
		nimln_(132, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_24 = addInt((*i), ((NI) 1));
		(*i) = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_24);
		nimln_(133, "uri.nim");
		T11_ = (NI)0;
		T11_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).query), TM_VzbRQH9cb1xm1tSKH4PwBSw_25, (*i));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_26 = addInt((*i), T11_);
		(*i) = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_26);
	}
	LA9_: ;
	nimln_(135, "uri.nim");
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_27;
		NI T16_;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_29;
		if ((NU)((*i)) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[(*i)]) == (NU8)(35))) goto LA14_;
		nimln_(136, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_27 = addInt((*i), ((NI) 1));
		(*i) = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_27);
		nimln_(137, "uri.nim");
		T16_ = (NI)0;
		T16_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&(*result).anchor), TM_VzbRQH9cb1xm1tSKH4PwBSw_28, (*i));
		TM_VzbRQH9cb1xm1tSKH4PwBSw_29 = addInt((*i), T16_);
		(*i) = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_29);
	}
	LA14_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initUri_KjX0htiF0llidA9bDLRUx0g)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	nimfr_("initUri", "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(141, "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	unsureAsgnRef((void**) (&(*Result).scheme), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).username), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).password), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).hostname), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).port), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).path), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).query), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	unsureAsgnRef((void**) (&(*Result).anchor), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, resetUri_p9buM2dTitsqXTMz6vOVUyQ)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri) {
	nimfr_("resetUri", "uri.nim");
	nimln_(147, "uri.nim");
	(*uri).scheme = setLengthStr((*uri).scheme, ((NI) 0));
	(*uri).username = setLengthStr((*uri).username, ((NI) 0));
	(*uri).password = setLengthStr((*uri).password, ((NI) 0));
	(*uri).hostname = setLengthStr((*uri).hostname, ((NI) 0));
	(*uri).port = setLengthStr((*uri).port, ((NI) 0));
	(*uri).path = setLengthStr((*uri).path, ((NI) 0));
	(*uri).query = setLengthStr((*uri).query, ((NI) 0));
	(*uri).anchor = setLengthStr((*uri).anchor, ((NI) 0));
	nimln_(149, "uri.nim");
	(*uri).opaque = NIM_FALSE;
	popFrame();
}

static N_INLINE(NI, parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri)(NimStringDesc* s, NimStringDesc** token, tySet_tyChar_nmiMWKVIe46vacnhAFrQvw validChars, NI start) {
	NI result;
	NI i;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_33;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_34;
	nimfr_("parseWhile", "parseutils.nim");
	result = (NI)0;
	nimln_(216, "parseutils.nim");
	i = start;
	{
		nimln_(217, "parseutils.nim");
		while (1) {
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_32;
			if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
			if (!((validChars[(NU)(((NU8)(s->data[i])))>>3] &(1U<<((NU)(((NU8)(s->data[i])))&7U)))!=0)) goto LA2;
			TM_VzbRQH9cb1xm1tSKH4PwBSw_32 = addInt(i, ((NI) 1));
			i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_32);
		} LA2: ;
	}
	nimln_(218, "parseutils.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_33 = subInt(i, start);
	result = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_33);
	nimln_(219, "parseutils.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_34 = subInt(i, ((NI) 1));
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_34)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseUri_rSbDZf9caa6pIyn5lw5aylw)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* result) {
	NI i;
	NIM_BOOL doubleSlash;
	NIM_BOOL T1_;
	NI T11_;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_36;
	nimfr_("parseUri", "uri.nim");
{	nimln_(153, "uri.nim");
	resetUri_p9buM2dTitsqXTMz6vOVUyQ(result);
	nimln_(155, "uri.nim");
	i = ((NI) 0);
	nimln_(158, "uri.nim");
	T1_ = (NIM_BOOL)0;
	T1_ = (((NI) 1) < (uri ? uri->Sup.len : 0));
	if (!(T1_)) goto LA2_;
	if ((NU)(((NI) 1)) > (NU)(uri->Sup.len)) raiseIndexError();
	T1_ = ((NU8)(uri->data[((NI) 1)]) == (NU8)(47));
	LA2_: ;
	doubleSlash = T1_;
	nimln_(159, "uri.nim");
	{
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		if (!((NU8)(uri->data[i]) == (NU8)(47))) goto LA5_;
		nimln_(161, "uri.nim");
		{
			if (!!(doubleSlash)) goto LA9_;
			nimln_(162, "uri.nim");
			parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
			nimln_(163, "uri.nim");
			goto BeforeRet_;
		}
		LA9_: ;
	}
	LA5_: ;
	nimln_(166, "uri.nim");
	T11_ = (NI)0;
	T11_ = parseWhile_nRS4GqEDZ9ccEUkAA5bRWgwuri(uri, (&(*result).scheme), TM_VzbRQH9cb1xm1tSKH4PwBSw_35, i);
	TM_VzbRQH9cb1xm1tSKH4PwBSw_36 = addInt(i, T11_);
	i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_36);
	nimln_(167, "uri.nim");
	{
		NIM_BOOL T14_;
		T14_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(167, "uri.nim");
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		T14_ = !(((NU8)(uri->data[i]) == (NU8)(58)));
		if (!(T14_)) goto LA15_;
		T14_ = !(doubleSlash);
		LA15_: ;
		if (!T14_) goto LA16_;
		nimln_(169, "uri.nim");
		i = ((NI) 0);
		nimln_(170, "uri.nim");
		(*result).scheme = setLengthStr((*result).scheme, ((NI) 0));
		nimln_(171, "uri.nim");
		parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
		nimln_(172, "uri.nim");
		goto BeforeRet_;
	}
	LA16_: ;
	nimln_(173, "uri.nim");
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_37;
		if (!!(doubleSlash)) goto LA20_;
		nimln_(174, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_37 = addInt(i, ((NI) 1));
		i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_37);
	}
	LA20_: ;
	nimln_(177, "uri.nim");
	{
		NIM_BOOL T24_;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_38;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_39;
		NimStringDesc* authority;
		NI T28_;
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_41;
		T24_ = (NIM_BOOL)0;
		if ((NU)(i) > (NU)(uri->Sup.len)) raiseIndexError();
		T24_ = ((NU8)(uri->data[i]) == (NU8)(47));
		if (!(T24_)) goto LA25_;
		TM_VzbRQH9cb1xm1tSKH4PwBSw_38 = addInt(i, ((NI) 1));
		if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_38)) > (NU)(uri->Sup.len)) raiseIndexError();
		T24_ = ((NU8)(uri->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_38)]) == (NU8)(47));
		LA25_: ;
		if (!T24_) goto LA26_;
		nimln_(178, "uri.nim");
		TM_VzbRQH9cb1xm1tSKH4PwBSw_39 = addInt(i, ((NI) 2));
		i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_39);
		nimln_(179, "uri.nim");
		authority = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31));
		nimln_(180, "uri.nim");
		T28_ = (NI)0;
		T28_ = parseUntil_zSglkPmqQkVaLkVSiDuiCguri(uri, (&authority), TM_VzbRQH9cb1xm1tSKH4PwBSw_40, i);
		TM_VzbRQH9cb1xm1tSKH4PwBSw_41 = addInt(i, T28_);
		i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_41);
		nimln_(181, "uri.nim");
		{
			if (!(((NI) 0) < (authority ? authority->Sup.len : 0))) goto LA31_;
			nimln_(182, "uri.nim");
			parseAuthority_MuG6s2bAvx9cZweCqxUbCdw(authority, result);
		}
		LA31_: ;
	}
	goto LA22_;
	LA26_: ;
	{
		nimln_(184, "uri.nim");
		(*result).opaque = NIM_TRUE;
	}
	LA22_: ;
	nimln_(187, "uri.nim");
	parsePath_Kk9czUCtpspxIGySYVuPs9bQ(uri, (&i), result);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseUri_HN0Rsm1KKAfXov53XGF88Q)(NimStringDesc* uri, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	nimfr_("parseUri", "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(191, "uri.nim");
	initUri_KjX0htiF0llidA9bDLRUx0g(Result);
	nimln_(192, "uri.nim");
	parseUri_rSbDZf9caa6pIyn5lw5aylw(uri, Result);
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, resize_bzF9a0JivP3Z4njqaxuLc5wsystem)(NI old) {
	NI result;
	result = (NI)0;
	{
		if (!(old <= ((NI) 0))) goto LA3_;
		result = ((NI) 4);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(old < ((NI) 65536))) goto LA6_;
		result = (NI)(old * ((NI) 2));
	}
	goto LA1_;
	LA6_: ;
	{
		result = (NI)((NI)(old * ((NI) 3)) / ((NI) 2));
	}
	LA1_: ;
	return result;
}

static N_INLINE(void, zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem)(void* p, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(p, ((int) 0), ((size_t) (size)));
}

static N_INLINE(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemSize, NI newLen) {
	TGenericSeq* result;
	result = (TGenericSeq*)0;
	result = seq;
	{
		NI r;
		NI T5_;
		void* T6_;
		if (!((NI)((*result).reserved & ((NI) IL64(4611686018427387903))) < newLen)) goto LA3_;
		T5_ = (NI)0;
		T5_ = resize_bzF9a0JivP3Z4njqaxuLc5wsystem((NI)((*result).reserved & ((NI) IL64(4611686018427387903))));
		r = ((T5_ >= newLen) ? T5_ : newLen);
		T6_ = (void*)0;
		T6_ = growObj_AVYny8c0GTk28gxjmat1MA(((void*) (result)), (NI)((NI)(elemSize * r) + ((NI) 16)));
		result = ((TGenericSeq*) (T6_));
		(*result).reserved = r;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!(newLen < (*result).len)) goto LA8_;
		{
			TNimType* T12_;
			T12_ = (TNimType*)0;
			T12_ = extGetCellType(((void*) (result)));
			if (!!((((*(*T12_).base).flags &(1U<<((NU)(((tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ) 0))&7U)))!=0))) goto LA13_;
			{
				NI i;
				NI colontmp_;
				NI res;
				i = (NI)0;
				colontmp_ = (NI)0;
				colontmp_ = (NI)((*result).len - ((NI) 1));
				res = newLen;
				{
					while (1) {
						TNimType* T18_;
						if (!(res <= colontmp_)) goto LA17;
						i = res;
						T18_ = (TNimType*)0;
						T18_ = extGetCellType(((void*) (result)));
						forAllChildrenAux_YOI1Uo54H9aas13WthjhsfA(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(i) * (NU64)(elemSize)))))), (*T18_).base, ((tyEnum_WalkOp_Wfy7gT5VQ8B3aJBxqU8D9cQ) 2));
						res += ((NI) 1);
					} LA17: ;
				}
			}
		}
		LA13_: ;
		zeroMem_t0o5XqKanO5QJfXMGEzp2Asystem(((void*) ((NI)((NU64)((NI)((NU64)(((NI) (ptrdiff_t) (result))) + (NU64)(((NI) 16)))) + (NU64)((NI)((NU64)(newLen) * (NU64)(elemSize)))))), ((NI) ((NI)((NU64)((NI)((NU64)((*result).len) - (NU64)(newLen))) * (NU64)(elemSize)))));
	}
	goto LA1_;
	LA8_: ;
	LA1_: ;
	(*result).len = newLen;
	return result;
}

static N_INLINE(NimStringDesc*, pop_9cDsfK2acP02vJ9bhxIE9caEAos)(tySequence_sM4lkSb7zS6F7OVMvW9cffQ** s) {
	NimStringDesc* result;
	NI L;
	NI T1_;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_45;
	nimfr_("pop", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(2431, "system.nim");
	T1_ = ((*s) ? (*s)->Sup.len : 0);
	TM_VzbRQH9cb1xm1tSKH4PwBSw_45 = subInt(T1_, ((NI) 1));
	L = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_45);
	nimln_(2432, "system.nim");
	if ((NU)(L) >= (NU)((*s)->Sup.len)) raiseIndexError();
	result = copyString((*s)->data[L]);
	nimln_(2433, "system.nim");
	(*s) = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) setLengthSeq(&((*s))->Sup, sizeof(NimStringDesc*), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ)(NimStringDesc* path) {
	NimStringDesc* result;
	tySequence_sM4lkSb7zS6F7OVMvW9cffQ* collection;
	NIM_BOOL endsWithSlash;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_42;
	NI i;
	NimStringDesc* currentSegment;
	nimfr_("removeDotSegments", "uri.nim");
{	result = (NimStringDesc*)0;
	nimln_(195, "uri.nim");
	{
		if (!((path ? path->Sup.len : 0) == ((NI) 0))) goto LA3_;
		result = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31));
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(196, "uri.nim");
	collection = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) newSeq((&NTI_sM4lkSb7zS6F7OVMvW9cffQ_), 0);
	nimln_(197, "uri.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_42 = subInt((path ? path->Sup.len : 0), ((NI) 1));
	if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_42)) > (NU)(path->Sup.len)) raiseIndexError();
	endsWithSlash = ((NU8)(path->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_42)]) == (NU8)(47));
	nimln_(198, "uri.nim");
	i = ((NI) 0);
	nimln_(199, "uri.nim");
	currentSegment = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31));
	{
		nimln_(200, "uri.nim");
		while (1) {
			{
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_49;
				nimln_(201, "uri.nim");
				if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
				switch (((NU8)(path->data[i]))) {
				case 47:
				{
					NI T9_;
					NimStringDesc* T10_;
					nimln_(203, "uri.nim");
					collection = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(collection)->Sup, sizeof(NimStringDesc*));
					T9_ = collection->Sup.len++;
					T10_ = (NimStringDesc*)0;
					T10_ = collection->data[T9_]; collection->data[T9_] = copyStringRC1(currentSegment);
					if (T10_) nimGCunrefNoCycle(T10_);
					nimln_(204, "uri.nim");
					currentSegment = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31));
				}
				break;
				case 46:
				{
					nimln_(206, "uri.nim");
					{
						NIM_BOOL T14_;
						NI TM_VzbRQH9cb1xm1tSKH4PwBSw_43;
						NI TM_VzbRQH9cb1xm1tSKH4PwBSw_44;
						T14_ = (NIM_BOOL)0;
						TM_VzbRQH9cb1xm1tSKH4PwBSw_43 = addInt(i, ((NI) 1));
						if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_43)) > (NU)(path->Sup.len)) raiseIndexError();
						T14_ = ((NU8)(path->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_43)]) == (NU8)(46));
						if (!(T14_)) goto LA15_;
						TM_VzbRQH9cb1xm1tSKH4PwBSw_44 = addInt(i, ((NI) 2));
						if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_44)) > (NU)(path->Sup.len)) raiseIndexError();
						T14_ = ((NU8)(path->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_44)]) == (NU8)(47));
						LA15_: ;
						if (!T14_) goto LA16_;
						nimln_(207, "uri.nim");
						{
							NI T20_;
							NimStringDesc* T23_;
							NI TM_VzbRQH9cb1xm1tSKH4PwBSw_46;
							T20_ = (collection ? collection->Sup.len : 0);
							if (!(((NI) 0) < T20_)) goto LA21_;
							nimln_(208, "uri.nim");
							T23_ = (NimStringDesc*)0;
							T23_ = pop_9cDsfK2acP02vJ9bhxIE9caEAos((&collection));
							T23_;
							nimln_(209, "uri.nim");
							TM_VzbRQH9cb1xm1tSKH4PwBSw_46 = addInt(i, ((NI) 3));
							i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_46);
							nimln_(210, "uri.nim");
							goto LA7;
						}
						LA21_: ;
					}
					goto LA12_;
					LA16_: ;
					{
						NI TM_VzbRQH9cb1xm1tSKH4PwBSw_47;
						NI TM_VzbRQH9cb1xm1tSKH4PwBSw_48;
						nimln_(211, "uri.nim");
						TM_VzbRQH9cb1xm1tSKH4PwBSw_47 = addInt(i, ((NI) 1));
						if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_47)) > (NU)(path->Sup.len)) raiseIndexError();
						if (!((NU8)(path->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_47)]) == (NU8)(47))) goto LA25_;
						nimln_(212, "uri.nim");
						TM_VzbRQH9cb1xm1tSKH4PwBSw_48 = addInt(i, ((NI) 2));
						i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_48);
						nimln_(213, "uri.nim");
						goto LA7;
					}
					goto LA12_;
					LA25_: ;
					LA12_: ;
					nimln_(214, "uri.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					currentSegment = addChar(currentSegment, path->data[i]);
				}
				break;
				case 0:
				{
					nimln_(216, "uri.nim");
					{
						NI T32_;
						NimStringDesc* T33_;
						nimln_(398, "system.nim");
						nimln_(216, "uri.nim");
						if (!!(((currentSegment) && (currentSegment)->Sup.len == 0))) goto LA30_;
						nimln_(217, "uri.nim");
						collection = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*) incrSeqV2(&(collection)->Sup, sizeof(NimStringDesc*));
						T32_ = collection->Sup.len++;
						T33_ = (NimStringDesc*)0;
						T33_ = collection->data[T32_]; collection->data[T32_] = copyStringRC1(currentSegment);
						if (T33_) nimGCunrefNoCycle(T33_);
					}
					LA30_: ;
					nimln_(218, "uri.nim");
					goto LA5;
				}
				break;
				default:
				{
					nimln_(220, "uri.nim");
					if ((NU)(i) > (NU)(path->Sup.len)) raiseIndexError();
					currentSegment = addChar(currentSegment, path->data[i]);
				}
				break;
				}
				nimln_(221, "uri.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_49 = addInt(i, ((NI) 1));
				i = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_49);
			} LA7: ;
		}
	} LA5: ;
	nimln_(223, "uri.nim");
	result = nsuJoinSep(collection->data, collection->Sup.len, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_50));
	nimln_(224, "uri.nim");
	{
		if (!endsWithSlash) goto LA37_;
		result = addChar(result, 47);
	}
	LA37_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest, NIM_CHAR c) {
	(*dest).data[((*dest).Sup.len)- 0] = c;
	(*dest).data[((NI)((*dest).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest).Sup.len += ((NI) 1);
}

static N_INLINE(NimStringDesc*, X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_51;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_52;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_51 = subInt(x.b, a);
	TM_VzbRQH9cb1xm1tSKH4PwBSw_52 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_51), ((NI) 1));
	L = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_52);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_53;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_54;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_53 = addInt(i, a);
				if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_53)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_53)];
				nimln_(3522, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_54 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_54);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qtimes)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, merge_18P4yVuuwO3AQV9a7ftFwqA)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* base, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* reference) {
	NimStringDesc* result;
	nimfr_("merge", "uri.nim");
	result = (NimStringDesc*)0;
	nimln_(228, "uri.nim");
	{
		NIM_BOOL T3_;
		NimStringDesc* T7_;
		T3_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(228, "uri.nim");
		T3_ = !((((*base).hostname) && ((*base).hostname)->Sup.len == 0));
		if (!(T3_)) goto LA4_;
		T3_ = (((*base).path) && ((*base).path)->Sup.len == 0);
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(229, "uri.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = rawNewString((*reference).path->Sup.len + 1);
appendChar(T7_, 47);
appendString(T7_, (*reference).path);
		result = T7_;
	}
	goto LA1_;
	LA5_: ;
	{
		NI lastSegment;
		nimln_(231, "uri.nim");
		lastSegment = rfind_GYN9aIPE4YImn9c3fuLInlTg((*base).path, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_50), ((NI) -1));
		nimln_(232, "uri.nim");
		{
			if (!(lastSegment == ((NI) -1))) goto LA11_;
			result = copyString((*reference).path);
		}
		goto LA9_;
		LA11_: ;
		{
			NimStringDesc* T14_;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T15_;
			NimStringDesc* T16_;
			nimln_(235, "uri.nim");
			T14_ = (NimStringDesc*)0;
			T15_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 0), lastSegment);
			T16_ = (NimStringDesc*)0;
			T16_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils((*base).path, T15_);
			T14_ = rawNewString(T16_->Sup.len + (*reference).path->Sup.len + 0);
appendString(T14_, T16_);
appendString(T14_, (*reference).path);
			result = T14_;
		}
		LA9_: ;
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, combine_VvDeUAddaSa6f9c4L9bbifew)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* base, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* reference, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	nimfr_("combine", "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(266, "uri.nim");
	initUri_KjX0htiF0llidA9bDLRUx0g(Result);
	nimln_(267, "uri.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		nimln_(398, "system.nim");
		nimln_(267, "uri.nim");
		T3_ = !(eqStrings((*reference).scheme, (*base).scheme));
		if (!(T3_)) goto LA4_;
		nimln_(398, "system.nim");
		nimln_(267, "uri.nim");
		T3_ = !((((*reference).scheme) && ((*reference).scheme)->Sup.len == 0));
		LA4_: ;
		if (!T3_) goto LA5_;
		nimln_(268, "uri.nim");
		genericAssign((void*)Result, (void*)reference, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
		nimln_(269, "uri.nim");
		unsureAsgnRef((void**) (&(*Result).path), removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ((*Result).path));
	}
	goto LA1_;
	LA5_: ;
	{
		nimln_(271, "uri.nim");
		{
			nimln_(398, "system.nim");
			nimln_(271, "uri.nim");
			if (!!((((*reference).hostname) && ((*reference).hostname)->Sup.len == 0))) goto LA10_;
			nimln_(261, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).hostname), copyString((*reference).hostname));
			nimln_(262, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).username), copyString((*reference).username));
			nimln_(263, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).port), copyString((*reference).port));
			nimln_(264, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).password), copyString((*reference).password));
			nimln_(273, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).path), removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ((*reference).path));
			nimln_(274, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).query), copyString((*reference).query));
		}
		goto LA8_;
		LA10_: ;
		{
			nimln_(276, "uri.nim");
			{
				if (!(((*reference).path) && ((*reference).path)->Sup.len == 0)) goto LA15_;
				nimln_(277, "uri.nim");
				unsureAsgnRef((void**) (&(*Result).path), copyString((*base).path));
				nimln_(278, "uri.nim");
				{
					nimln_(398, "system.nim");
					nimln_(278, "uri.nim");
					if (!!((((*reference).query) && ((*reference).query)->Sup.len == 0))) goto LA19_;
					nimln_(279, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).query), copyString((*reference).query));
				}
				goto LA17_;
				LA19_: ;
				{
					nimln_(281, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).query), copyString((*base).query));
				}
				LA17_: ;
			}
			goto LA13_;
			LA15_: ;
			{
				nimln_(283, "uri.nim");
				{
					NIM_BOOL T25_;
					T25_ = (NIM_BOOL)0;
					T25_ = nsuStartsWith((*reference).path, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_50));
					if (!T25_) goto LA26_;
					nimln_(284, "uri.nim");
					unsureAsgnRef((void**) (&(*Result).path), removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ((*reference).path));
				}
				goto LA23_;
				LA26_: ;
				{
					NimStringDesc* T29_;
					nimln_(286, "uri.nim");
					T29_ = (NimStringDesc*)0;
					T29_ = merge_18P4yVuuwO3AQV9a7ftFwqA(base, reference);
					unsureAsgnRef((void**) (&(*Result).path), removeDotSegments_mjPhxt678AYBCtIUKN9ajiQ(T29_));
				}
				LA23_: ;
				nimln_(287, "uri.nim");
				unsureAsgnRef((void**) (&(*Result).query), copyString((*reference).query));
			}
			LA13_: ;
			nimln_(261, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).hostname), copyString((*base).hostname));
			nimln_(262, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).username), copyString((*base).username));
			nimln_(263, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).port), copyString((*base).port));
			nimln_(264, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).password), copyString((*base).password));
		}
		LA8_: ;
		nimln_(289, "uri.nim");
		unsureAsgnRef((void**) (&(*Result).scheme), copyString((*base).scheme));
	}
	LA1_: ;
	nimln_(290, "uri.nim");
	unsureAsgnRef((void**) (&(*Result).anchor), copyString((*reference).anchor));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, combine_t58oLEw9ciSu2pjqeOck9azg)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uris, NI urisLen_0, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	nimfr_("combine", "uri.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(294, "uri.nim");
	if ((NU)(((NI) 0)) >= (NU)(urisLen_0)) raiseIndexError();
	genericAssign((void*)Result, (void*)(&uris[((NI) 0)]), (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	{
		NI i;
		NI colontmp_;
		NI i_2;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(295, "uri.nim");
		colontmp_ = urisLen_0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 1);
		{
			nimln_(3520, "system.nim");
			while (1) {
				tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ T4_;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_55;
				if (!(i_2 < colontmp_)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				nimln_(296, "uri.nim");
				if ((NU)(i) >= (NU)(urisLen_0)) raiseIndexError();
				memset((void*)(&T4_), 0, sizeof(T4_));
				combine_VvDeUAddaSa6f9c4L9bbifew(Result, (&uris[i]), (&T4_));
				genericShallowAssign((void*)Result, (void*)(&T4_), (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
				nimln_(3522, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_55 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_55);
			} LA3: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isAbsolute_qN9cts56Np81Y0BUTVYLZ4A)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* uri) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T3_;
	nimfr_("isAbsolute", "uri.nim");
{	result = (NIM_BOOL)0;
	nimln_(300, "uri.nim");
	T1_ = (NIM_BOOL)0;
	nimln_(398, "system.nim");
	nimln_(300, "uri.nim");
	T1_ = !((((*uri).scheme) && ((*uri).scheme)->Sup.len == 0));
	if (!(T1_)) goto LA2_;
	T3_ = (NIM_BOOL)0;
	nimln_(398, "system.nim");
	nimln_(300, "uri.nim");
	T3_ = !((((*uri).hostname) && ((*uri).hostname)->Sup.len == 0));
	if (T3_) goto LA4_;
	nimln_(398, "system.nim");
	nimln_(300, "uri.nim");
	T3_ = !((((*uri).path) && ((*uri).path)->Sup.len == 0));
	LA4_: ;
	T1_ = T3_;
	LA2_: ;
	result = T1_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, slash__zM0XqLEoeXfdWrrSUdJ9c4g)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* x, NimStringDesc* path, tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* Result) {
	nimfr_("/", "uri.nim");
{	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(320, "uri.nim");
	genericAssign((void*)Result, (void*)x, (&NTI_j49bukNPrq747O1GRd4Ng9bQ_));
	nimln_(322, "uri.nim");
	{
		if (!(((*Result).path ? (*Result).path->Sup.len : 0) == ((NI) 0))) goto LA3_;
		nimln_(323, "uri.nim");
		{
			nimln_(398, "system.nim");
			nimln_(323, "uri.nim");
			if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
			if (!!(((NU8)(path->data[((NI) 0)]) == (NU8)(47)))) goto LA7_;
			nimln_(324, "uri.nim");
			unsureAsgnRef((void**) (&(*Result).path), copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_50)));
		}
		LA7_: ;
		nimln_(325, "uri.nim");
		(*Result).path = resizeString((*Result).path, path->Sup.len + 0);
appendString((*Result).path, path);
		nimln_(326, "uri.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(328, "uri.nim");
	{
		NI TM_VzbRQH9cb1xm1tSKH4PwBSw_56;
		TM_VzbRQH9cb1xm1tSKH4PwBSw_56 = subInt(((*Result).path ? (*Result).path->Sup.len : 0), ((NI) 1));
		if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_56)) > (NU)((*Result).path->Sup.len)) raiseIndexError();
		if (!((NU8)((*Result).path->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_56)]) == (NU8)(47))) goto LA11_;
		nimln_(329, "uri.nim");
		{
			NI TM_VzbRQH9cb1xm1tSKH4PwBSw_57;
			tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T17_;
			NimStringDesc* T18_;
			if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
			if (!((NU8)(path->data[((NI) 0)]) == (NU8)(47))) goto LA15_;
			nimln_(330, "uri.nim");
			TM_VzbRQH9cb1xm1tSKH4PwBSw_57 = subInt((path ? path->Sup.len : 0), ((NI) 1));
			T17_ = dotdot__vDQySKWzgnxQdUarow6k5Qtimes(((NI) 1), (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_57));
			T18_ = (NimStringDesc*)0;
			T18_ = X5BX5D__xiaaX9b4cczHG39bivOynT9bgstrutils(path, T17_);
			(*Result).path = resizeString((*Result).path, T18_->Sup.len + 0);
appendString((*Result).path, T18_);
		}
		goto LA13_;
		LA15_: ;
		{
			nimln_(332, "uri.nim");
			(*Result).path = resizeString((*Result).path, path->Sup.len + 0);
appendString((*Result).path, path);
		}
		LA13_: ;
	}
	goto LA9_;
	LA11_: ;
	{
		nimln_(334, "uri.nim");
		{
			nimln_(398, "system.nim");
			nimln_(334, "uri.nim");
			if ((NU)(((NI) 0)) > (NU)(path->Sup.len)) raiseIndexError();
			if (!!(((NU8)(path->data[((NI) 0)]) == (NU8)(47)))) goto LA23_;
			nimln_(335, "uri.nim");
			(*Result).path = addChar((*Result).path, 47);
		}
		LA23_: ;
		nimln_(336, "uri.nim");
		(*Result).path = resizeString((*Result).path, path->Sup.len + 0);
appendString((*Result).path, path);
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, endsWith_znzByIhLc10EfS4jWWkP2wuri)(NimStringDesc* s, NIM_CHAR suffix) {
	NIM_BOOL result;
	nimfr_("endsWith", "strutils.nim");
	result = (NIM_BOOL)0;
	result = ((NU8)(s->data[(s ? (s->Sup.len-1) : -1)]) == (NU8)(suffix));
	popFrame();
	return result;
}

static N_INLINE(NimStringDesc*, X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils)(NimStringDesc* s, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x) {
	NimStringDesc* result;
	NI a;
	NI L;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_61;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_62;
	NI TM_VzbRQH9cb1xm1tSKH4PwBSw_63;
	nimfr_("[]", "system.nim");
	result = (NimStringDesc*)0;
	nimln_(3556, "system.nim");
	a = x.a;
	nimln_(3557, "system.nim");
	nimln_(3546, "system.nim");
	nimln_(3557, "system.nim");
	TM_VzbRQH9cb1xm1tSKH4PwBSw_61 = subInt((s ? s->Sup.len : 0), x.b);
	TM_VzbRQH9cb1xm1tSKH4PwBSw_62 = subInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_61), a);
	TM_VzbRQH9cb1xm1tSKH4PwBSw_63 = addInt((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_62), ((NI) 1));
	L = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_63);
	nimln_(3558, "system.nim");
	result = mnewString(((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i;
		NI i_2;
		i = (NI)0;
		nimln_(3519, "system.nim");
		i_2 = ((NI) 0);
		{
			nimln_(3520, "system.nim");
			while (1) {
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_64;
				NI TM_VzbRQH9cb1xm1tSKH4PwBSw_65;
				if (!(i_2 < L)) goto LA3;
				nimln_(3521, "system.nim");
				i = i_2;
				if ((NU)(i) > (NU)(result->Sup.len)) raiseIndexError();
				nimln_(3559, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_64 = addInt(i, a);
				if ((NU)((NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_64)) > (NU)(s->Sup.len)) raiseIndexError();
				result->data[i] = s->data[(NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_64)];
				nimln_(3522, "system.nim");
				TM_VzbRQH9cb1xm1tSKH4PwBSw_65 = addInt(i_2, ((NI) 1));
				i_2 = (NI)(TM_VzbRQH9cb1xm1tSKH4PwBSw_65);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__ctxq0YSon7aLz7isCROwwQuri)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	nimfr_("..", "system.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(325, "system.nim");
	result.a = a;
	nimln_(326, "system.nim");
	result.b = b;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Q6hX9cwycP8fRn52OpcLEjw)(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ* u) {
	NimStringDesc* result;
	nimfr_("$", "uri.nim");
	result = (NimStringDesc*)0;
	nimln_(340, "uri.nim");
	result = copyString(((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_31));
	nimln_(341, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).scheme ? (*u).scheme->Sup.len : 0))) goto LA3_;
		nimln_(342, "uri.nim");
		result = resizeString(result, (*u).scheme->Sup.len + 0);
appendString(result, (*u).scheme);
		nimln_(343, "uri.nim");
		{
			if (!(*u).opaque) goto LA7_;
			nimln_(344, "uri.nim");
			result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_58));
		}
		goto LA5_;
		LA7_: ;
		{
			nimln_(346, "uri.nim");
			result = resizeString(result, 3);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_59));
		}
		LA5_: ;
	}
	LA3_: ;
	nimln_(347, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).username ? (*u).username->Sup.len : 0))) goto LA12_;
		nimln_(348, "uri.nim");
		result = resizeString(result, (*u).username->Sup.len + 0);
appendString(result, (*u).username);
		nimln_(349, "uri.nim");
		{
			if (!(((NI) 0) < ((*u).password ? (*u).password->Sup.len : 0))) goto LA16_;
			nimln_(350, "uri.nim");
			result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_58));
			nimln_(351, "uri.nim");
			result = resizeString(result, (*u).password->Sup.len + 0);
appendString(result, (*u).password);
		}
		LA16_: ;
		nimln_(352, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_60));
	}
	LA12_: ;
	nimln_(353, "uri.nim");
	{
		NIM_BOOL T20_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T23_;
		NimStringDesc* T24_;
		T20_ = (NIM_BOOL)0;
		T20_ = endsWith_znzByIhLc10EfS4jWWkP2wuri((*u).hostname, 47);
		if (!T20_) goto LA21_;
		nimln_(354, "uri.nim");
		T23_ = dotdot__ctxq0YSon7aLz7isCROwwQuri(((NI) 0), ((NI) 2));
		T24_ = (NimStringDesc*)0;
		T24_ = X5BX5D__lkBUIkH7j2jb0vaXPf2frAstrutils((*u).hostname, T23_);
		result = resizeString(result, T24_->Sup.len + 0);
appendString(result, T24_);
	}
	goto LA18_;
	LA21_: ;
	{
		nimln_(356, "uri.nim");
		result = resizeString(result, (*u).hostname->Sup.len + 0);
appendString(result, (*u).hostname);
	}
	LA18_: ;
	nimln_(357, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).port ? (*u).port->Sup.len : 0))) goto LA28_;
		nimln_(358, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_58));
		nimln_(359, "uri.nim");
		result = resizeString(result, (*u).port->Sup.len + 0);
appendString(result, (*u).port);
	}
	LA28_: ;
	nimln_(360, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).path ? (*u).path->Sup.len : 0))) goto LA32_;
		nimln_(361, "uri.nim");
		{
			NIM_BOOL T36_;
			T36_ = (NIM_BOOL)0;
			T36_ = (((NI) 0) < ((*u).hostname ? (*u).hostname->Sup.len : 0));
			if (!(T36_)) goto LA37_;
			nimln_(398, "system.nim");
			nimln_(361, "uri.nim");
			if ((NU)(((NI) 0)) > (NU)((*u).path->Sup.len)) raiseIndexError();
			T36_ = !(((NU8)((*u).path->data[((NI) 0)]) == (NU8)(47)));
			LA37_: ;
			if (!T36_) goto LA38_;
			nimln_(362, "uri.nim");
			result = addChar(result, 47);
		}
		LA38_: ;
		nimln_(363, "uri.nim");
		result = resizeString(result, (*u).path->Sup.len + 0);
appendString(result, (*u).path);
	}
	LA32_: ;
	nimln_(364, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).query ? (*u).query->Sup.len : 0))) goto LA42_;
		nimln_(365, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_66));
		nimln_(366, "uri.nim");
		result = resizeString(result, (*u).query->Sup.len + 0);
appendString(result, (*u).query);
	}
	LA42_: ;
	nimln_(367, "uri.nim");
	{
		if (!(((NI) 0) < ((*u).anchor ? (*u).anchor->Sup.len : 0))) goto LA46_;
		nimln_(368, "uri.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_VzbRQH9cb1xm1tSKH4PwBSw_67));
		nimln_(369, "uri.nim");
		result = resizeString(result, (*u).anchor->Sup.len + 0);
appendString(result, (*u).anchor);
	}
	LA46_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_uriInit000)(void) {
	nimfr_("uri", "uri.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_uriDatInit000)(void) {
static TNimNode* TM_VzbRQH9cb1xm1tSKH4PwBSw_30[9];
static TNimNode TM_VzbRQH9cb1xm1tSKH4PwBSw_0[10];
NTI_j49bukNPrq747O1GRd4Ng9bQ_.size = sizeof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ);
NTI_j49bukNPrq747O1GRd4Ng9bQ_.kind = 18;
NTI_j49bukNPrq747O1GRd4Ng9bQ_.base = 0;
NTI_j49bukNPrq747O1GRd4Ng9bQ_.flags = 2;
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[0] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, scheme);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[1].name = "scheme";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[1] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, username);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[2].name = "username";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[2] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, password);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[3].name = "password";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[3] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, hostname);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[4].name = "hostname";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[4] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, port);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[5].name = "port";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[5] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, path);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[6].name = "path";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[6] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, query);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[7].name = "query";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[7] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, anchor);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[8].name = "anchor";
TM_VzbRQH9cb1xm1tSKH4PwBSw_30[8] = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9];
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].kind = 1;
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].offset = offsetof(tyObject_Uri_j49bukNPrq747O1GRd4Ng9bQ, opaque);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[9].name = "opaque";
TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].len = 9; TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].kind = 2; TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0].sons = &TM_VzbRQH9cb1xm1tSKH4PwBSw_30[0];
NTI_j49bukNPrq747O1GRd4Ng9bQ_.node = &TM_VzbRQH9cb1xm1tSKH4PwBSw_0[0];
}

