/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_cstrutils.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/stdlib_cstrutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
static N_INLINE(NIM_CHAR, toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils)(NIM_CHAR c);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, csuStartsWith)(NCSTRING s, NCSTRING prefix);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, csuEndsWith)(NCSTRING s, NCSTRING suffix);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NI, csuCmpIgnoreStyle)(NCSTRING a, NCSTRING b);
N_LIB_PRIVATE N_NIMCALL(NI, csuCmpIgnoreCase)(NCSTRING a, NCSTRING b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_CHAR, toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils)(NIM_CHAR c) {
	NIM_CHAR result;
	nimfr_("toLowerAscii", "cstrutils.nim");
	result = (NIM_CHAR)0;
	nimln_(17, "cstrutils.nim");
	{
		NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_2;
		if (!(((NU8)(c)) >= ((NU8)(65)) && ((NU8)(c)) <= ((NU8)(90)))) goto LA3_;
		nimln_(18, "cstrutils.nim");
		TM_is8NdSOqVDyl9a9bWX7JQtCQ_2 = addInt(((NU8)(c)), ((NI) 32));
		result = ((NIM_CHAR) (((NI)chckRange((NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_2), ((NI) 0), ((NI) 255)))));
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(20, "cstrutils.nim");
		result = c;
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, csuStartsWith)(NCSTRING s, NCSTRING prefix) {
	NIM_BOOL result;
	NI i;
	nimfr_("startsWith", "cstrutils.nim");
{	result = (NIM_BOOL)0;
	nimln_(27, "cstrutils.nim");
	i = ((NI) 0);
	{
		nimln_(28, "cstrutils.nim");
		while (1) {
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_3;
			nimln_(29, "cstrutils.nim");
			{
				if (!((NU8)(prefix[i]) == (NU8)(0))) goto LA5_;
				result = NIM_TRUE;
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(30, "cstrutils.nim");
			{
				nimln_(398, "system.nim");
				nimln_(30, "cstrutils.nim");
				if (!!(((NU8)(s[i]) == (NU8)(prefix[i])))) goto LA9_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(31, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_3 = addInt(i, ((NI) 1));
			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_3);
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, csuEndsWith)(NCSTRING s, NCSTRING suffix) {
	NIM_BOOL result;
	NI slen;
	NI i;
	NI j;
	NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_4;
	nimfr_("endsWith", "cstrutils.nim");
{	result = (NIM_BOOL)0;
	nimln_(38, "cstrutils.nim");
	slen = (s ? strlen(s) : 0);
	nimln_(39, "cstrutils.nim");
	i = ((NI) 0);
	nimln_(40, "cstrutils.nim");
	TM_is8NdSOqVDyl9a9bWX7JQtCQ_4 = subInt(slen, (suffix ? strlen(suffix) : 0));
	j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_4);
	{
		nimln_(41, "cstrutils.nim");
		while (1) {
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_5;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_7;
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_5 = addInt(i, j);
			if (!((NU64)((NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_5)) < (NU64)(slen))) goto LA2;
			nimln_(42, "cstrutils.nim");
			{
				NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_6;
				nimln_(398, "system.nim");
				nimln_(42, "cstrutils.nim");
				TM_is8NdSOqVDyl9a9bWX7JQtCQ_6 = addInt(i, j);
				if (!!(((NU8)(s[(NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_6)]) == (NU8)(suffix[i])))) goto LA5_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
			LA5_: ;
			nimln_(43, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_7 = addInt(i, ((NI) 1));
			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_7);
		} LA2: ;
	}
	nimln_(44, "cstrutils.nim");
	{
		if (!((NU8)(suffix[i]) == (NU8)(0))) goto LA9_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA9_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, csuCmpIgnoreStyle)(NCSTRING a, NCSTRING b) {
	NI result;
	NI i;
	NI j;
	nimfr_("cmpIgnoreStyle", "cstrutils.nim");
	result = (NI)0;
	nimln_(54, "cstrutils.nim");
	i = ((NI) 0);
	nimln_(55, "cstrutils.nim");
	j = ((NI) 0);
	{
		nimln_(56, "cstrutils.nim");
		while (1) {
			NIM_CHAR aa;
			NIM_CHAR bb;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_10;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_11;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_12;
			{
				nimln_(57, "cstrutils.nim");
				while (1) {
					NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_8;
					if (!((NU8)(a[i]) == (NU8)(95))) goto LA4;
					TM_is8NdSOqVDyl9a9bWX7JQtCQ_8 = addInt(i, ((NI) 1));
					i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_8);
				} LA4: ;
			}
			{
				nimln_(58, "cstrutils.nim");
				while (1) {
					NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_9;
					if (!((NU8)(b[j]) == (NU8)(95))) goto LA6;
					TM_is8NdSOqVDyl9a9bWX7JQtCQ_9 = addInt(j, ((NI) 1));
					j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_9);
				} LA6: ;
			}
			nimln_(59, "cstrutils.nim");
			aa = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(a[i]);
			nimln_(60, "cstrutils.nim");
			bb = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(b[j]);
			nimln_(61, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_10 = subInt(((NU8)(aa)), ((NU8)(bb)));
			result = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_10);
			nimln_(62, "cstrutils.nim");
			{
				NIM_BOOL T9_;
				T9_ = (NIM_BOOL)0;
				nimln_(398, "system.nim");
				nimln_(62, "cstrutils.nim");
				T9_ = !((result == ((NI) 0)));
				if (T9_) goto LA10_;
				T9_ = ((NU8)(aa) == (NU8)(0));
				LA10_: ;
				if (!T9_) goto LA11_;
				goto LA1;
			}
			LA11_: ;
			nimln_(63, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_11 = addInt(i, ((NI) 1));
			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_11);
			nimln_(64, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_12 = addInt(j, ((NI) 1));
			j = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_12);
		}
	} LA1: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, csuCmpIgnoreCase)(NCSTRING a, NCSTRING b) {
	NI result;
	NI i;
	nimfr_("cmpIgnoreCase", "cstrutils.nim");
	result = (NI)0;
	nimln_(73, "cstrutils.nim");
	i = ((NI) 0);
	{
		nimln_(74, "cstrutils.nim");
		while (1) {
			NIM_CHAR aa;
			NIM_CHAR bb;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_13;
			NI TM_is8NdSOqVDyl9a9bWX7JQtCQ_14;
			nimln_(75, "cstrutils.nim");
			aa = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(a[i]);
			nimln_(76, "cstrutils.nim");
			bb = toLowerAscii_FrOxGR15qwSoYjNe5m1QjQcstrutils(b[i]);
			nimln_(77, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_13 = subInt(((NU8)(aa)), ((NU8)(bb)));
			result = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_13);
			nimln_(78, "cstrutils.nim");
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				nimln_(398, "system.nim");
				nimln_(78, "cstrutils.nim");
				T5_ = !((result == ((NI) 0)));
				if (T5_) goto LA6_;
				T5_ = ((NU8)(aa) == (NU8)(0));
				LA6_: ;
				if (!T5_) goto LA7_;
				goto LA1;
			}
			LA7_: ;
			nimln_(79, "cstrutils.nim");
			TM_is8NdSOqVDyl9a9bWX7JQtCQ_14 = addInt(i, ((NI) 1));
			i = (NI)(TM_is8NdSOqVDyl9a9bWX7JQtCQ_14);
		}
	} LA1: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsInit000)(void) {
	nimfr_("cstrutils", "cstrutils.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_cstrutilsDatInit000)(void) {
}

