/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/telebot_keyboard.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/telebot_keyboard.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w;
typedef struct tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA;
typedef struct tySequence_8VADr7ryTOpS9bss4JUVjuA tySequence_8VADr7ryTOpS9bss4JUVjuA;
typedef struct tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg;
typedef struct RootObj RootObj;
typedef struct tySequence_cJ8gMIqFMgnntDtYbWTxyA tySequence_cJ8gMIqFMgnntDtYbWTxyA;
typedef struct tySequence_nLegeRq4u39bO9bq3o7h9bgxQ tySequence_nLegeRq4u39bO9bq3o7h9bgxQ;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg;
typedef struct tyObject_Option_NougmKhcNEDOkPwUwWSKYA tyObject_Option_NougmKhcNEDOkPwUwWSKYA;
typedef struct tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w;
typedef struct tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg;
typedef struct tySequence_dx1Y4RLNWyRhYer29a6dDhw tySequence_dx1Y4RLNWyRhYer29a6dDhw;
typedef struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q;
typedef struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw;
typedef struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g tySequence_MlAD6nAPq9bHKla9cWiIZP0g;
typedef struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ tySequence_oLpBKXzW3hF9aCVMo5EymfQ;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyTuple_awOivLjlO76sGdHY7nQUjQ tyTuple_awOivLjlO76sGdHY7nQUjQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w {
NIM_BOOL val;
NIM_BOOL has;
};
struct tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA {
NimStringDesc* text;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w requestContact;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w requestLocation;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg {
  RootObj Sup;
};
typedef NU8 tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw;
struct tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA {
  tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg Sup;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w selective;
tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw kind;
union{
struct {tySequence_cJ8gMIqFMgnntDtYbWTxyA* keyboard;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w resizeKeyboard;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w oneTimeKeyboard;
} S1;
struct {tySequence_nLegeRq4u39bO9bq3o7h9bgxQ* inlineKeyboard;
} S2;
} kindU;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Option_NougmKhcNEDOkPwUwWSKYA {
NimStringDesc* val;
NIM_BOOL has;
};
struct tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg {
  tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg Sup;
};
struct tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w {
tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg val;
NIM_BOOL has;
};
struct tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg {
NimStringDesc* text;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA url;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA callbackData;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA switchInlineQuery;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA switchInlineQueryCurrentChat;
tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w callbackGame;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w pay;
};
typedef NU8 tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg;
struct tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw {
tySequence_MlAD6nAPq9bHKla9cWiIZP0g* data;
NI counter;
NI first;
NI last;
};
struct tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q {
tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg kind;
union{
struct {NimStringDesc* str;
} S1;
struct {NI64 num;
} S2;
struct {NF fnum;
} S3;
struct {NIM_BOOL bval;
} S4;
struct {tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw fields;
} S6;
struct {tySequence_oLpBKXzW3hF9aCVMo5EymfQ* elems;
} S7;
} kindU;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyTuple_awOivLjlO76sGdHY7nQUjQ {
NI Field0;
NI Field1;
NimStringDesc* Field2;
tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* Field3;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_8VADr7ryTOpS9bss4JUVjuA {
  TGenericSeq Sup;
  tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA data[SEQ_DECL_SIZE];
};
struct tySequence_cJ8gMIqFMgnntDtYbWTxyA {
  TGenericSeq Sup;
  tySequence_8VADr7ryTOpS9bss4JUVjuA* data[SEQ_DECL_SIZE];
};
struct tySequence_dx1Y4RLNWyRhYer29a6dDhw {
  TGenericSeq Sup;
  tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg data[SEQ_DECL_SIZE];
};
struct tySequence_nLegeRq4u39bO9bq3o7h9bgxQ {
  TGenericSeq Sup;
  tySequence_dx1Y4RLNWyRhYer29a6dDhw* data[SEQ_DECL_SIZE];
};
struct tySequence_MlAD6nAPq9bHKla9cWiIZP0g {
  TGenericSeq Sup;
  tyTuple_awOivLjlO76sGdHY7nQUjQ data[SEQ_DECL_SIZE];
};
struct tySequence_oLpBKXzW3hF9aCVMo5EymfQ {
  TGenericSeq Sup;
  tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(void, initKeyBoardButton_AlTHGRjeoTOlODbLI7tRsg)(NimStringDesc* text, tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newReplyKeyboardMarkup_CR3Jg9bkZcC8cfnUAm42BeA)(tySequence_8VADr7ryTOpS9bss4JUVjuA** keyboards, NI keyboardsLen_0);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(void, FieldDiscriminantCheck)(NI oldDiscVal, NI newDiscVal, TNimNode** a, NI L);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(void, genericSeqAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, initInlineKeyBoardButton_ytokUixH0BJ9aXR4DiDhZcw)(NimStringDesc* text, tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg* Result);
N_NIMCALL(void, objectInit)(void* dest, TNimType* typ);
N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newInlineKeyboardMarkup_u79aW3Q4lxjH0nYJDgTvA6g)(tySequence_dx1Y4RLNWyRhYer29a6dDhw** keyboards, NI keyboardsLen_0);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newReplyKeyboardRemove_HfT9ckdA1zgP1asuopCUMiQ)(NIM_BOOL selective);
N_LIB_PRIVATE N_NIMCALL(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w, some_fznRoWAaJZjGeOxDOI8BhQ)(NIM_BOOL val);
N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newForceReply_HfT9ckdA1zgP1asuopCUMiQ_2)(NIM_BOOL selective);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Uqs0IB7GB2zuj89ad1VSOvQ)(tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA k);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJObject_phgxr9cKlc0dmrJpCth52pw_2)(void);
static N_INLINE(void, X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q)(tyObject_OrderedTable_AF39bJ7XDr6gpANuGpxkHrw* t, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__8iXO9aRAijCPe58pujCBbuQ_3)(NimStringDesc* s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, get_72BWCcuQaOgbEmHle9b43gw)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w self);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJBool_bESUahFJIJ0RSySOPtSYZg)(NIM_BOOL b);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__f9cKpuwjrLNwYtym1kuFzjQ)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* node);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__wsuAy4BxsgY6FlJdPuEuiQ)(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* k);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJArray_phgxr9cKlc0dmrJpCth52pw_3)(void);
N_LIB_PRIVATE N_NIMCALL(void, add_NE4BWkXVxUMFtDmmA5ZcHw)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* father, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* child);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__a5yu9aeSLz1kws3PVPOB3Uw)(tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA o);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_72BWCcuQaOgbEmHle9b43gw_3)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w self);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__5iJ6ASFRuC4duZuGXhmsTQ)(tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg* o);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_72BWCcuQaOgbEmHle9b43gw_2)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w self);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__GwiVl8umr4gmrd7azkqPwgjson)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w o);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__bESUahFJIJ0RSySOPtSYZg_2)(NIM_BOOL b);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, newJNull_phgxr9cKlc0dmrJpCth52pw)(void);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__XRYOunFMXCeHdJU43d9bM5wjson)(tyObject_Option_NougmKhcNEDOkPwUwWSKYA o);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_Vf0P9aShtGNxd0LRCDsFTRA_2)(tyObject_Option_NougmKhcNEDOkPwUwWSKYA self);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, get_BHbuFDwVg35aUZJPDRlzPw)(tyObject_Option_NougmKhcNEDOkPwUwWSKYA self);
static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__ULvdItMU9czAqStCP9b9cJYTAjson)(tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w o);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_wWHbJ1HYV1aGKQxXqByh0w)(tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w self);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__pzttyCW4e0fR9ah7lvE2zPw)(tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg* o);
N_LIB_PRIVATE N_NIMCALL(void, get_GiK49c5XCLF9cJzlImavbviw)(tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w self, tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg* Result);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_wWHbJ1HYV1aGKQxXqByh0w_2)(tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w self);
extern TNimType NTI_BmmSNtdvLhe2WZR0VF83KA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_pP1OCphkq2wPy9cnA6ojHAg_;
extern TNimType NTI_EvY1OP9aa3R9czBoj9cQqwTmA_;
extern TNimNode* NimDT__EvY1OP9aa3R9czBoj9cQqwTmA_kind[5];
extern TNimType NTI_cJ8gMIqFMgnntDtYbWTxyA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_8VADr7ryTOpS9bss4JUVjuA_;
extern TNimType NTI_qt9b19ciUotg9bNBKc851JwEg_;
extern TNimType NTI_nLegeRq4u39bO9bq3o7h9bgxQ_;
extern TNimType NTI_dx1Y4RLNWyRhYer29a6dDhw_;
extern TNimType NTI_HDAwA4LwA2dSG29b5ZmBHmg_;
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_2, "keyboard", 8);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_4, "inlineKeyboard", 14);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_6, "obj.kind == JObject ", 20);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_7, "fields", 6);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_8, "text", 4);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_9, "request_contact", 15);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_10, "request_location", 16);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_12, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_14, "keyboard", 8);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_15, "selective", 9);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_16, "resizeKeyboard", 14);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_17, "resize_keyboard", 15);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_18, "oneTimeKeyboard", 15);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_19, "one_time_keyboard", 17);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_22, "inline_keyboard", 15);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_23, "{\'remove_keyboard\': true}", 25);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_24, "{\'remove_keyboard\': true, \'selective\': true}", 44);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_25, "{\'force_reply\': true}", 21);
STRING_LITERAL(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_26, "{\'force_reply\': true, \'selective\': true}", 40);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, initKeyBoardButton_AlTHGRjeoTOlODbLI7tRsg)(NimStringDesc* text, tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA* Result) {
	nimfr_("initKeyBoardButton", "keyboard.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_BmmSNtdvLhe2WZR0VF83KA_));
	nimln_(4, "keyboard.nim");
	unsureAsgnRef((void**) (&(*Result).text), copyString(text));
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newReplyKeyboardMarkup_CR3Jg9bkZcC8cfnUAm42BeA)(tySequence_8VADr7ryTOpS9bss4JUVjuA** keyboards, NI keyboardsLen_0) {
	tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* result;
	tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw T1_;
	nimfr_("newReplyKeyboardMarkup", "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*)0;
	nimln_(7, "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*) newObj((&NTI_pP1OCphkq2wPy9cnA6ojHAg_), sizeof(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA));
	(*result).Sup.Sup.m_type = (&NTI_EvY1OP9aa3R9czBoj9cQqwTmA_);
	nimln_(8, "keyboard.nim");
	T1_ = (tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw)0;
	T1_ = ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 0);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__EvY1OP9aa3R9czBoj9cQqwTmA_kind, 5);
	(*result).kind = T1_;
	if (!(((1 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_2));
	nimln_(9, "keyboard.nim");
	if ((*result).kindU.S1.keyboard) { nimGCunrefNoCycle((*result).kindU.S1.keyboard); (*result).kindU.S1.keyboard = NIM_NIL; }
	(*result).kindU.S1.keyboard = (tySequence_cJ8gMIqFMgnntDtYbWTxyA*) newSeqRC1((&NTI_cJ8gMIqFMgnntDtYbWTxyA_), 0);
	{
		tySequence_8VADr7ryTOpS9bss4JUVjuA* keyboard;
		NI i;
		keyboard = (tySequence_8VADr7ryTOpS9bss4JUVjuA*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI T5_;
				NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_3;
				if (!(i < keyboardsLen_0)) goto LA4;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(keyboardsLen_0)) raiseIndexError();
				keyboard = keyboards[i];
				nimln_(11, "keyboard.nim");
				if (!(((1 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_2));
				(*result).kindU.S1.keyboard = (tySequence_cJ8gMIqFMgnntDtYbWTxyA*) incrSeqV2(&((*result).kindU.S1.keyboard)->Sup, sizeof(tySequence_8VADr7ryTOpS9bss4JUVjuA*));
				T5_ = (*result).kindU.S1.keyboard->Sup.len++;
				genericSeqAssign((&(*result).kindU.S1.keyboard->data[T5_]), keyboard, (&NTI_8VADr7ryTOpS9bss4JUVjuA_));
				nimln_(2188, "system.nim");
				TM_Gr4LMd8HvLBEiMMSQ4u5Xg_3 = addInt(i, ((NI) 1));
				i = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_3);
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initInlineKeyBoardButton_ytokUixH0BJ9aXR4DiDhZcw)(NimStringDesc* text, tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg* Result) {
	nimfr_("initInlineKeyBoardButton", "keyboard.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_qt9b19ciUotg9bNBKc851JwEg_));
	objectInit(Result, (&NTI_qt9b19ciUotg9bNBKc851JwEg_));
	nimln_(14, "keyboard.nim");
	unsureAsgnRef((void**) (&(*Result).text), copyString(text));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newInlineKeyboardMarkup_u79aW3Q4lxjH0nYJDgTvA6g)(tySequence_dx1Y4RLNWyRhYer29a6dDhw** keyboards, NI keyboardsLen_0) {
	tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* result;
	tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw T1_;
	nimfr_("newInlineKeyboardMarkup", "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*)0;
	nimln_(17, "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*) newObj((&NTI_pP1OCphkq2wPy9cnA6ojHAg_), sizeof(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA));
	(*result).Sup.Sup.m_type = (&NTI_EvY1OP9aa3R9czBoj9cQqwTmA_);
	nimln_(18, "keyboard.nim");
	T1_ = (tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw)0;
	T1_ = ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 3);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__EvY1OP9aa3R9czBoj9cQqwTmA_kind, 5);
	(*result).kind = T1_;
	if (!(((8 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_4));
	nimln_(19, "keyboard.nim");
	if ((*result).kindU.S2.inlineKeyboard) { nimGCunrefRC1((*result).kindU.S2.inlineKeyboard); (*result).kindU.S2.inlineKeyboard = NIM_NIL; }
	(*result).kindU.S2.inlineKeyboard = (tySequence_nLegeRq4u39bO9bq3o7h9bgxQ*) newSeqRC1((&NTI_nLegeRq4u39bO9bq3o7h9bgxQ_), 0);
	{
		tySequence_dx1Y4RLNWyRhYer29a6dDhw* keyboard;
		NI i;
		keyboard = (tySequence_dx1Y4RLNWyRhYer29a6dDhw*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NI T5_;
				NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_5;
				if (!(i < keyboardsLen_0)) goto LA4;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(keyboardsLen_0)) raiseIndexError();
				keyboard = keyboards[i];
				nimln_(21, "keyboard.nim");
				if (!(((8 &(1U<<((NU)((*result).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_4));
				(*result).kindU.S2.inlineKeyboard = (tySequence_nLegeRq4u39bO9bq3o7h9bgxQ*) incrSeqV2(&((*result).kindU.S2.inlineKeyboard)->Sup, sizeof(tySequence_dx1Y4RLNWyRhYer29a6dDhw*));
				T5_ = (*result).kindU.S2.inlineKeyboard->Sup.len++;
				genericSeqAssign((&(*result).kindU.S2.inlineKeyboard->data[T5_]), keyboard, (&NTI_dx1Y4RLNWyRhYer29a6dDhw_));
				nimln_(2188, "system.nim");
				TM_Gr4LMd8HvLBEiMMSQ4u5Xg_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_5);
			} LA4: ;
		}
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newReplyKeyboardRemove_HfT9ckdA1zgP1asuopCUMiQ)(NIM_BOOL selective) {
	tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* result;
	tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw T1_;
	nimfr_("newReplyKeyboardRemove", "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*)0;
	nimln_(24, "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*) newObj((&NTI_pP1OCphkq2wPy9cnA6ojHAg_), sizeof(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA));
	(*result).Sup.Sup.m_type = (&NTI_EvY1OP9aa3R9czBoj9cQqwTmA_);
	nimln_(25, "keyboard.nim");
	T1_ = (tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw)0;
	T1_ = ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 1);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__EvY1OP9aa3R9czBoj9cQqwTmA_kind, 5);
	(*result).kind = T1_;
	nimln_(26, "keyboard.nim");
	(*result).selective = some_fznRoWAaJZjGeOxDOI8BhQ(selective);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*, newForceReply_HfT9ckdA1zgP1asuopCUMiQ_2)(NIM_BOOL selective) {
	tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* result;
	tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw T1_;
	nimfr_("newForceReply", "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*)0;
	nimln_(29, "keyboard.nim");
	result = (tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA*) newObj((&NTI_pP1OCphkq2wPy9cnA6ojHAg_), sizeof(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA));
	(*result).Sup.Sup.m_type = (&NTI_EvY1OP9aa3R9czBoj9cQqwTmA_);
	nimln_(30, "keyboard.nim");
	T1_ = (tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw)0;
	T1_ = ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 2);
	FieldDiscriminantCheck((NI)(NU)((*result).kind), (NI)(NU)(T1_), NimDT__EvY1OP9aa3R9czBoj9cQqwTmA_kind, 5);
	(*result).kind = T1_;
	nimln_(31, "keyboard.nim");
	(*result).selective = some_fznRoWAaJZjGeOxDOI8BhQ(selective);
	popFrame();
	return result;
}

static N_INLINE(void, X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson)(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* obj, NimStringDesc* key, tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* val) {
	nimfr_("[]=", "json.nim");
	nimln_(954, "json.nim");
	{
		if (!!(((*obj).kind == ((tyEnum_JsonNodeKind_RUngo7nCHe6O8aBGIcrhtg) 5)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_6));
	}
	LA3_: ;
	nimln_(955, "json.nim");
	if (!(((32 &(1U<<((NU)((*obj).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_7));
	X5BX5Deq__9bwm9c9bGAcoIGLjRndWCPT3Q((&(*obj).kindU.S6.fields), key, val);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__Uqs0IB7GB2zuj89ad1VSOvQ)(tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA k) {
	NimStringDesc* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T1_;
	nimfr_("$", "keyboard.nim");
	result = (NimStringDesc*)0;
	nimln_(34, "keyboard.nim");
	j = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
	nimln_(35, "keyboard.nim");
	T1_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	T1_ = percent__8iXO9aRAijCPe58pujCBbuQ_3(k.text);
	X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_8), T1_);
	nimln_(36, "keyboard.nim");
	{
		NIM_BOOL T4_;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T7_;
		T4_ = (NIM_BOOL)0;
		T4_ = get_72BWCcuQaOgbEmHle9b43gw(k.requestContact);
		if (!T4_) goto LA5_;
		nimln_(37, "keyboard.nim");
		T7_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		T7_ = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
		X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_9), T7_);
	}
	LA5_: ;
	nimln_(38, "keyboard.nim");
	{
		NIM_BOOL T10_;
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T13_;
		T10_ = (NIM_BOOL)0;
		T10_ = get_72BWCcuQaOgbEmHle9b43gw(k.requestLocation);
		if (!T10_) goto LA11_;
		nimln_(39, "keyboard.nim");
		T13_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
		T13_ = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
		X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_10), T13_);
	}
	LA11_: ;
	nimln_(41, "keyboard.nim");
	result = dollar__f9cKpuwjrLNwYtym1kuFzjQ(j);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__wsuAy4BxsgY6FlJdPuEuiQ)(tyObject_KeyboardMarkupcolonObjectType__EvY1OP9aa3R9czBoj9cQqwTmA* k) {
	NimStringDesc* result;
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* j;
	nimfr_("$", "keyboard.nim");
{	result = (NimStringDesc*)0;
	nimln_(44, "keyboard.nim");
	j = newJObject_phgxr9cKlc0dmrJpCth52pw_2();
	nimln_(45, "keyboard.nim");
	switch ((*k).kind) {
	case ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 0):
	{
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* kb;
		nimln_(48, "keyboard.nim");
		kb = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		{
			tySequence_8VADr7ryTOpS9bss4JUVjuA* row;
			tySequence_cJ8gMIqFMgnntDtYbWTxyA* colontmp_;
			NI i;
			NI L;
			NI T3_;
			row = (tySequence_8VADr7ryTOpS9bss4JUVjuA*)0;
			colontmp_ = (tySequence_cJ8gMIqFMgnntDtYbWTxyA*)0;
			nimln_(49, "keyboard.nim");
			if (!(((1 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_2));
			colontmp_ = (*k).kindU.S1.keyboard;
			nimln_(3805, "system.nim");
			i = ((NI) 0);
			nimln_(3806, "system.nim");
			T3_ = (colontmp_ ? colontmp_->Sup.len : 0);
			L = T3_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n;
					NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_13;
					if (!(i < L)) goto LA5;
					nimln_(3808, "system.nim");
					if ((NU)(i) >= (NU)(colontmp_->Sup.len)) raiseIndexError();
					row = colontmp_->data[i];
					nimln_(50, "keyboard.nim");
					n = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
					{
						tyObject_KeyboardButton_BmmSNtdvLhe2WZR0VF83KA button;
						NI i_2;
						NI L_2;
						NI T7_;
						memset((void*)(&button), 0, sizeof(button));
						nimln_(3805, "system.nim");
						i_2 = ((NI) 0);
						nimln_(3806, "system.nim");
						T7_ = (row ? row->Sup.len : 0);
						L_2 = T7_;
						{
							nimln_(3807, "system.nim");
							while (1) {
								tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T10_;
								NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_11;
								if (!(i_2 < L_2)) goto LA9;
								nimln_(3808, "system.nim");
								if ((NU)(i_2) >= (NU)(row->Sup.len)) raiseIndexError();
								button.text = row->data[i_2].text;
								button.requestContact = row->data[i_2].requestContact;
								button.requestLocation = row->data[i_2].requestLocation;
								nimln_(52, "keyboard.nim");
								T10_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
								T10_ = percent__a5yu9aeSLz1kws3PVPOB3Uw(button);
								add_NE4BWkXVxUMFtDmmA5ZcHw(n, T10_);
								nimln_(3809, "system.nim");
								TM_Gr4LMd8HvLBEiMMSQ4u5Xg_11 = addInt(i_2, ((NI) 1));
								i_2 = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_11);
								nimln_(3810, "system.nim");
								{
									NI T13_;
									T13_ = (row ? row->Sup.len : 0);
									if (!!((T13_ == L_2))) goto LA14_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_12));
								}
								LA14_: ;
							} LA9: ;
						}
					}
					nimln_(53, "keyboard.nim");
					add_NE4BWkXVxUMFtDmmA5ZcHw(kb, n);
					nimln_(3809, "system.nim");
					TM_Gr4LMd8HvLBEiMMSQ4u5Xg_13 = addInt(i, ((NI) 1));
					i = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_13);
					nimln_(3810, "system.nim");
					{
						NI T18_;
						T18_ = (colontmp_ ? colontmp_->Sup.len : 0);
						if (!!((T18_ == L))) goto LA19_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_12));
					}
					LA19_: ;
				} LA5: ;
			}
		}
		nimln_(54, "keyboard.nim");
		X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_14), kb);
		nimln_(55, "keyboard.nim");
		{
			NIM_BOOL T23_;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T27_;
			T23_ = (NIM_BOOL)0;
			T23_ = isSome_72BWCcuQaOgbEmHle9b43gw_3((*k).selective);
			if (!(T23_)) goto LA24_;
			T23_ = get_72BWCcuQaOgbEmHle9b43gw((*k).selective);
			LA24_: ;
			if (!T23_) goto LA25_;
			nimln_(56, "keyboard.nim");
			T27_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T27_ = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
			X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_15), T27_);
		}
		LA25_: ;
		nimln_(57, "keyboard.nim");
		{
			NIM_BOOL T30_;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T34_;
			T30_ = (NIM_BOOL)0;
			if (!(((1 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_16));
			T30_ = isSome_72BWCcuQaOgbEmHle9b43gw_3((*k).kindU.S1.resizeKeyboard);
			if (!(T30_)) goto LA31_;
			if (!(((1 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_16));
			T30_ = get_72BWCcuQaOgbEmHle9b43gw((*k).kindU.S1.resizeKeyboard);
			LA31_: ;
			if (!T30_) goto LA32_;
			nimln_(58, "keyboard.nim");
			T34_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T34_ = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
			X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_17), T34_);
		}
		LA32_: ;
		nimln_(59, "keyboard.nim");
		{
			NIM_BOOL T37_;
			tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T41_;
			T37_ = (NIM_BOOL)0;
			if (!(((1 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_18));
			T37_ = isSome_72BWCcuQaOgbEmHle9b43gw_3((*k).kindU.S1.oneTimeKeyboard);
			if (!(T37_)) goto LA38_;
			if (!(((1 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_18));
			T37_ = get_72BWCcuQaOgbEmHle9b43gw((*k).kindU.S1.oneTimeKeyboard);
			LA38_: ;
			if (!T37_) goto LA39_;
			nimln_(60, "keyboard.nim");
			T41_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
			T41_ = newJBool_bESUahFJIJ0RSySOPtSYZg(NIM_TRUE);
			X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_19), T41_);
		}
		LA39_: ;
	}
	break;
	case ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 3):
	{
		tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* kb_2;
		nimln_(62, "keyboard.nim");
		kb_2 = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
		{
			tySequence_dx1Y4RLNWyRhYer29a6dDhw* row_2;
			tySequence_nLegeRq4u39bO9bq3o7h9bgxQ* colontmp__2;
			NI i_3;
			NI L_3;
			NI T44_;
			row_2 = (tySequence_dx1Y4RLNWyRhYer29a6dDhw*)0;
			colontmp__2 = (tySequence_nLegeRq4u39bO9bq3o7h9bgxQ*)0;
			nimln_(63, "keyboard.nim");
			if (!(((8 &(1U<<((NU)((*k).kind)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_4));
			colontmp__2 = (*k).kindU.S2.inlineKeyboard;
			nimln_(3805, "system.nim");
			i_3 = ((NI) 0);
			nimln_(3806, "system.nim");
			T44_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
			L_3 = T44_;
			{
				nimln_(3807, "system.nim");
				while (1) {
					tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* n_2;
					NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_21;
					if (!(i_3 < L_3)) goto LA46;
					nimln_(3808, "system.nim");
					if ((NU)(i_3) >= (NU)(colontmp__2->Sup.len)) raiseIndexError();
					row_2 = colontmp__2->data[i_3];
					nimln_(64, "keyboard.nim");
					n_2 = newJArray_phgxr9cKlc0dmrJpCth52pw_3();
					{
						tyObject_InlineKeyboardButton_qt9b19ciUotg9bNBKc851JwEg button_2;
						NI i_4;
						NI L_4;
						NI T48_;
						memset((void*)(&button_2), 0, sizeof(button_2));
						objectInit((&button_2), (&NTI_qt9b19ciUotg9bNBKc851JwEg_));
						nimln_(3805, "system.nim");
						i_4 = ((NI) 0);
						nimln_(3806, "system.nim");
						T48_ = (row_2 ? row_2->Sup.len : 0);
						L_4 = T48_;
						{
							nimln_(3807, "system.nim");
							while (1) {
								tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* T51_;
								NI TM_Gr4LMd8HvLBEiMMSQ4u5Xg_20;
								if (!(i_4 < L_4)) goto LA50;
								nimln_(3808, "system.nim");
								if ((NU)(i_4) >= (NU)(row_2->Sup.len)) raiseIndexError();
								memcpy((void*)(&button_2), (NIM_CONST void*)(&row_2->data[i_4]), sizeof(button_2));
								nimln_(66, "keyboard.nim");
								T51_ = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
								T51_ = percent__5iJ6ASFRuC4duZuGXhmsTQ((&button_2));
								add_NE4BWkXVxUMFtDmmA5ZcHw(n_2, T51_);
								nimln_(3809, "system.nim");
								TM_Gr4LMd8HvLBEiMMSQ4u5Xg_20 = addInt(i_4, ((NI) 1));
								i_4 = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_20);
								nimln_(3810, "system.nim");
								{
									NI T54_;
									T54_ = (row_2 ? row_2->Sup.len : 0);
									if (!!((T54_ == L_4))) goto LA55_;
									failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_12));
								}
								LA55_: ;
							} LA50: ;
						}
					}
					nimln_(67, "keyboard.nim");
					add_NE4BWkXVxUMFtDmmA5ZcHw(kb_2, n_2);
					nimln_(3809, "system.nim");
					TM_Gr4LMd8HvLBEiMMSQ4u5Xg_21 = addInt(i_3, ((NI) 1));
					i_3 = (NI)(TM_Gr4LMd8HvLBEiMMSQ4u5Xg_21);
					nimln_(3810, "system.nim");
					{
						NI T59_;
						T59_ = (colontmp__2 ? colontmp__2->Sup.len : 0);
						if (!!((T59_ == L_3))) goto LA60_;
						failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_12));
					}
					LA60_: ;
				} LA46: ;
			}
		}
		nimln_(68, "keyboard.nim");
		X5BX5Deq__zgnKRzXVFYWnC0JSg1UbAQjson(j, ((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_22), kb_2);
	}
	break;
	case ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 1):
	{
		nimln_(70, "keyboard.nim");
		{
			NIM_BOOL T65_;
			NIM_BOOL T67_;
			T65_ = (NIM_BOOL)0;
			T65_ = isNone_72BWCcuQaOgbEmHle9b43gw_2((*k).selective);
			if (T65_) goto LA66_;
			T67_ = (NIM_BOOL)0;
			T67_ = get_72BWCcuQaOgbEmHle9b43gw((*k).selective);
			T65_ = !(T67_);
			LA66_: ;
			if (!T65_) goto LA68_;
			nimln_(71, "keyboard.nim");
			result = copyString(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_23));
			goto BeforeRet_;
		}
		goto LA63_;
		LA68_: ;
		{
			nimln_(73, "keyboard.nim");
			result = copyString(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_24));
			goto BeforeRet_;
		}
		LA63_: ;
	}
	break;
	case ((tyEnum_KeyboardKind_Hs39bUZcqIYyCXOy9c0cKwtw) 2):
	{
		nimln_(75, "keyboard.nim");
		{
			NIM_BOOL T74_;
			NIM_BOOL T76_;
			T74_ = (NIM_BOOL)0;
			T74_ = isNone_72BWCcuQaOgbEmHle9b43gw_2((*k).selective);
			if (T74_) goto LA75_;
			T76_ = (NIM_BOOL)0;
			T76_ = get_72BWCcuQaOgbEmHle9b43gw((*k).selective);
			T74_ = !(T76_);
			LA75_: ;
			if (!T74_) goto LA77_;
			nimln_(76, "keyboard.nim");
			result = copyString(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_25));
			goto BeforeRet_;
		}
		goto LA72_;
		LA77_: ;
		{
			nimln_(78, "keyboard.nim");
			result = copyString(((NimStringDesc*) &TM_Gr4LMd8HvLBEiMMSQ4u5Xg_26));
			goto BeforeRet_;
		}
		LA72_: ;
	}
	break;
	}
	nimln_(80, "keyboard.nim");
	result = dollar__f9cKpuwjrLNwYtym1kuFzjQ(j);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__GwiVl8umr4gmrd7azkqPwgjson)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w o) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("%", "utils.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(172, "utils.nim");
	{
		NIM_BOOL T3_;
		NIM_BOOL T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_72BWCcuQaOgbEmHle9b43gw_3(o);
		if (!T3_) goto LA4_;
		nimln_(173, "utils.nim");
		T6_ = (NIM_BOOL)0;
		T6_ = get_72BWCcuQaOgbEmHle9b43gw(o);
		result = percent__bESUahFJIJ0RSySOPtSYZg_2(T6_);
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(175, "utils.nim");
		result = newJNull_phgxr9cKlc0dmrJpCth52pw();
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__XRYOunFMXCeHdJU43d9bM5wjson)(tyObject_Option_NougmKhcNEDOkPwUwWSKYA o) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("%", "utils.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(172, "utils.nim");
	{
		NIM_BOOL T3_;
		NimStringDesc* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_Vf0P9aShtGNxd0LRCDsFTRA_2(o);
		if (!T3_) goto LA4_;
		nimln_(173, "utils.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = get_BHbuFDwVg35aUZJPDRlzPw(o);
		result = percent__8iXO9aRAijCPe58pujCBbuQ_3(T6_);
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(175, "utils.nim");
		result = newJNull_phgxr9cKlc0dmrJpCth52pw();
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*, percent__ULvdItMU9czAqStCP9b9cJYTAjson)(tyObject_Option_8VbBQvYbnxQpwa3yrp8O0w o) {
	tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q* result;
	nimfr_("%", "utils.nim");
	result = (tyObject_JsonNodeObj_df9bshXB7C9cTiWPIOtX3j1Q*)0;
	nimln_(172, "utils.nim");
	{
		NIM_BOOL T3_;
		tyObject_CallbackGame_HDAwA4LwA2dSG29b5ZmBHmg T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = isSome_wWHbJ1HYV1aGKQxXqByh0w(o);
		if (!T3_) goto LA4_;
		nimln_(173, "utils.nim");
		memset((void*)(&T6_), 0, sizeof(T6_));
		T6_.Sup.Sup.m_type = (&NTI_HDAwA4LwA2dSG29b5ZmBHmg_);
		get_GiK49c5XCLF9cJzlImavbviw(o, (&T6_));
		result = percent__pzttyCW4e0fR9ah7lvE2zPw((&T6_));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(175, "utils.nim");
		result = newJNull_phgxr9cKlc0dmrJpCth52pw();
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, telebot_keyboardInit000)(void) {
	nimfr_("keyboard", "keyboard.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, telebot_keyboardDatInit000)(void) {
}

