/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: MacOSX, amd64, clang */
/* Command for C compiler:
   clang -c  -w  -I/Users/niko/projects/homebrew/Cellar/nim/0.18.0_1/nim/lib -o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/telebot_inputmedia.o /Users/niko/Dropbox/BOOKS2/APRESS/02-nim/nimcache/telebot_inputmedia.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw;
typedef struct tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg;
typedef struct RootObj RootObj;
typedef struct tyObject_Option_NougmKhcNEDOkPwUwWSKYA tyObject_Option_NougmKhcNEDOkPwUwWSKYA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA;
typedef struct tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg;
typedef struct tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ;
typedef struct tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA;
typedef struct tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg;
typedef struct tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct RootObj {
TNimType* m_type;
};
struct tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg {
  RootObj Sup;
};
struct tyObject_Option_NougmKhcNEDOkPwUwWSKYA {
NimStringDesc* val;
NIM_BOOL has;
};
struct tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g {
  tyObject_TelegramObject_z0M5A185II9bS9cNZCcEO6Tg Sup;
NimStringDesc* kind;
NimStringDesc* media;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA thumb;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA caption;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA parseMode;
};
struct tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw {
  tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg {
NI val;
NIM_BOOL has;
};
struct tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w {
NIM_BOOL val;
NIM_BOOL has;
};
struct tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA {
  tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g Sup;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg width;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg height;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg duration;
tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w supportsStreaming;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg {
  tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g Sup;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg duration;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA performer;
tyObject_Option_NougmKhcNEDOkPwUwWSKYA title;
};
struct tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ {
  tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g Sup;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg width;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg height;
tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg duration;
};
struct tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA {
  tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g Sup;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__cquqxDlij2MteZZ779akGDg)(tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g* m);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, marshal_9cCqOHlXHzso9bQ6q8IM49cvA)(tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw* t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(void, marshal_FTwVrQfHi9bV0dgFE59cxmwg)(tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA* t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(void, marshal_QLGh22Y4OKjX7GsJyUBUvg)(tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg* t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(void, marshal_iYdp9aP9b9cqEvIQxAdrhrzFg)(tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ* t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(void, marshal_9aeXV4hBGz3QRRY9bwcWzQ0A)(tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA* t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw*, newInputMediaPhoto_9clpmM39a8d7U3MnBFN9aMyAg)(NimStringDesc* media, NimStringDesc* caption, NimStringDesc* parseMode);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_LIB_PRIVATE N_NIMCALL(void, some_SwTVedX6u26EmBXAZK9aBGQ)(NimStringDesc* val, tyObject_Option_NougmKhcNEDOkPwUwWSKYA* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA*, newInputMediaVideo_nYVSsOCCA6HzO73529bRw3w)(NimStringDesc* media, NimStringDesc* caption, NimStringDesc* parseMode);
N_LIB_PRIVATE N_NIMCALL(void, marshal_tKMZIAcoo9a57yPUt25hE3w)(NimStringDesc* t, NimStringDesc** s);
static N_INLINE(NIM_BOOL, isSet_8PWlY8kKGx8aCdLMEwqrqgutils)(NimStringDesc* value);
N_LIB_PRIVATE N_NIMCALL(void, marshal_9bJDMfLjcp0bTktMeGpQk0A)(tyObject_Option_NougmKhcNEDOkPwUwWSKYA t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isSome_wI8cvoqPi0pTcoxqWaMEag)(tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg self);
N_LIB_PRIVATE N_NIMCALL(void, marshal_xsM8dexLivJ9cCpSjvwJgEQ)(tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isNone_wI8cvoqPi0pTcoxqWaMEag_2)(tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg self);
N_LIB_PRIVATE N_NIMCALL(NI, get_3efsoaRwas0CuhT6EnyeIw)(tyObject_Option_T88g9alXWIDzxaB9cr0hjiMg self);
N_LIB_PRIVATE N_NIMCALL(void, marshal_GkAz5N23OkbzMZybkIBW8w)(NI t, NimStringDesc** s);
static N_INLINE(NIM_BOOL, isSet_c1CqxABvDHekt9adqRAlPOAutils)(NI value);
N_LIB_PRIVATE N_NIMCALL(void, marshal_aQeKthnPgqk7NOfG9auGY3g)(tyObject_Option_NyAW4Wujs3uzxhBe7ufz5w t, NimStringDesc** s);
N_LIB_PRIVATE N_NIMCALL(void, marshal_ClflIPBvzofHD7H8RrHE1A)(NIM_BOOL t, NimStringDesc** s);
static N_INLINE(NIM_BOOL, isSet_IBcRMEnyISyQB5bbGEgm1gutils)(NIM_BOOL value);
extern TNimType NTI_wEHZPBAXiBg3NLmmEwwnSw_;
static TNimType* Nim_OfCheck_CACHE4[2];
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_ivV9a0uQ528FMU9ckx09caadA_;
static TNimType* Nim_OfCheck_CACHE6[2];
extern TNimType NTI_9cBut4GWSXDiUMFNH6hRGjg_;
static TNimType* Nim_OfCheck_CACHE7[2];
extern TNimType NTI_270GK47XeUNMc0tKeJtL9bQ_;
static TNimType* Nim_OfCheck_CACHE8[2];
extern TNimType NTI_ybwcZvXFAD4ekW9bDKCa3zA_;
static TNimType* Nim_OfCheck_CACHE9[2];
extern TNimType NTI_gmn705d6zWQypPpfx1f9aYA_;
extern TNimType NTI_eQmQXwBiuObcDeJE2oPhdg_;
STRING_LITERAL(TM_QXH8VU509af4FifdjedxZFA_2, "", 0);
STRING_LITERAL(TM_QXH8VU509af4FifdjedxZFA_4, "photo", 5);
STRING_LITERAL(TM_QXH8VU509af4FifdjedxZFA_9, "video", 5);

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__cquqxDlij2MteZZ779akGDg)(tyObject_InputMediacolonObjectType__1nhSHooWWQttHJsHRzRe8g* m) {
	NimStringDesc* result;
	nimfr_("$", "inputmedia.nim");
	result = (NimStringDesc*)0;
	nimln_(4, "inputmedia.nim");
	result = copyString(((NimStringDesc*) &TM_QXH8VU509af4FifdjedxZFA_2));
	nimln_(5, "inputmedia.nim");
	{
		tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw* photo;
		NimStringDesc* T5_;
		if (!((m) && (isObjWithCache((*m).Sup.Sup.m_type, (&NTI_wEHZPBAXiBg3NLmmEwwnSw_), Nim_OfCheck_CACHE4)))) goto LA3_;
		nimln_(6, "inputmedia.nim");
		if (m) chckObj((*m).Sup.Sup.m_type, (&NTI_wEHZPBAXiBg3NLmmEwwnSw_));
		photo = ((tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw*) (m));
		nimln_(7, "inputmedia.nim");
		T5_ = (NimStringDesc*)0;
		T5_ = (*photo).Sup.kind; (*photo).Sup.kind = copyStringRC1(((NimStringDesc*) &TM_QXH8VU509af4FifdjedxZFA_4));
		if (T5_) nimGCunrefNoCycle(T5_);
		nimln_(8, "inputmedia.nim");
		marshal_9cCqOHlXHzso9bQ6q8IM49cvA((&(*photo)), (&result));
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA* video;
		nimln_(9, "inputmedia.nim");
		if (!((m) && (isObjWithCache((*m).Sup.Sup.m_type, (&NTI_ivV9a0uQ528FMU9ckx09caadA_), Nim_OfCheck_CACHE6)))) goto LA7_;
		nimln_(10, "inputmedia.nim");
		if (m) chckObj((*m).Sup.Sup.m_type, (&NTI_ivV9a0uQ528FMU9ckx09caadA_));
		video = ((tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA*) (m));
		nimln_(11, "inputmedia.nim");
		marshal_FTwVrQfHi9bV0dgFE59cxmwg((&(*video)), (&result));
	}
	goto LA1_;
	LA7_: ;
	{
		tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg* audio;
		nimln_(12, "inputmedia.nim");
		if (!((m) && (isObjWithCache((*m).Sup.Sup.m_type, (&NTI_9cBut4GWSXDiUMFNH6hRGjg_), Nim_OfCheck_CACHE7)))) goto LA10_;
		nimln_(13, "inputmedia.nim");
		if (m) chckObj((*m).Sup.Sup.m_type, (&NTI_9cBut4GWSXDiUMFNH6hRGjg_));
		audio = ((tyObject_InputMediaAudiocolonObjectType__9cBut4GWSXDiUMFNH6hRGjg*) (m));
		nimln_(14, "inputmedia.nim");
		marshal_QLGh22Y4OKjX7GsJyUBUvg((&(*audio)), (&result));
	}
	goto LA1_;
	LA10_: ;
	{
		tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ* animation;
		nimln_(15, "inputmedia.nim");
		if (!((m) && (isObjWithCache((*m).Sup.Sup.m_type, (&NTI_270GK47XeUNMc0tKeJtL9bQ_), Nim_OfCheck_CACHE8)))) goto LA13_;
		nimln_(16, "inputmedia.nim");
		if (m) chckObj((*m).Sup.Sup.m_type, (&NTI_270GK47XeUNMc0tKeJtL9bQ_));
		animation = ((tyObject_InputMediaAnimationcolonObjectType__270GK47XeUNMc0tKeJtL9bQ*) (m));
		nimln_(17, "inputmedia.nim");
		marshal_iYdp9aP9b9cqEvIQxAdrhrzFg((&(*animation)), (&result));
	}
	goto LA1_;
	LA13_: ;
	{
		tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA* document;
		nimln_(18, "inputmedia.nim");
		if (!((m) && (isObjWithCache((*m).Sup.Sup.m_type, (&NTI_ybwcZvXFAD4ekW9bDKCa3zA_), Nim_OfCheck_CACHE9)))) goto LA16_;
		nimln_(19, "inputmedia.nim");
		if (m) chckObj((*m).Sup.Sup.m_type, (&NTI_ybwcZvXFAD4ekW9bDKCa3zA_));
		document = ((tyObject_InputMediaDocumentcolonObjectType__ybwcZvXFAD4ekW9bDKCa3zA*) (m));
		nimln_(20, "inputmedia.nim");
		marshal_9aeXV4hBGz3QRRY9bwcWzQ0A((&(*document)), (&result));
	}
	goto LA1_;
	LA16_: ;
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw*, newInputMediaPhoto_9clpmM39a8d7U3MnBFN9aMyAg)(NimStringDesc* media, NimStringDesc* caption, NimStringDesc* parseMode) {
	tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("newInputMediaPhoto", "inputmedia.nim");
	result = (tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw*)0;
	nimln_(22, "inputmedia.nim");
	result = (tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw*) newObj((&NTI_gmn705d6zWQypPpfx1f9aYA_), sizeof(tyObject_InputMediaPhotocolonObjectType__wEHZPBAXiBg3NLmmEwwnSw));
	(*result).Sup.Sup.Sup.m_type = (&NTI_wEHZPBAXiBg3NLmmEwwnSw_);
	nimln_(23, "inputmedia.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Sup.kind; (*result).Sup.kind = copyStringRC1(((NimStringDesc*) &TM_QXH8VU509af4FifdjedxZFA_4));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(24, "inputmedia.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = (*result).Sup.media; (*result).Sup.media = copyStringRC1(media);
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(25, "inputmedia.nim");
	{
		if (!(((NI) 0) < (caption ? caption->Sup.len : 0))) goto LA5_;
		nimln_(26, "inputmedia.nim");
		some_SwTVedX6u26EmBXAZK9aBGQ(caption, (&(*result).Sup.caption));
	}
	LA5_: ;
	nimln_(27, "inputmedia.nim");
	{
		if (!(((NI) 0) < (parseMode ? parseMode->Sup.len : 0))) goto LA9_;
		nimln_(28, "inputmedia.nim");
		some_SwTVedX6u26EmBXAZK9aBGQ(parseMode, (&(*result).Sup.parseMode));
	}
	LA9_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA*, newInputMediaVideo_nYVSsOCCA6HzO73529bRw3w)(NimStringDesc* media, NimStringDesc* caption, NimStringDesc* parseMode) {
	tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA* result;
	NimStringDesc* T1_;
	NimStringDesc* T2_;
	nimfr_("newInputMediaVideo", "inputmedia.nim");
	result = (tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA*)0;
	nimln_(31, "inputmedia.nim");
	result = (tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA*) newObj((&NTI_eQmQXwBiuObcDeJE2oPhdg_), sizeof(tyObject_InputMediaVideocolonObjectType__ivV9a0uQ528FMU9ckx09caadA));
	(*result).Sup.Sup.Sup.m_type = (&NTI_ivV9a0uQ528FMU9ckx09caadA_);
	nimln_(32, "inputmedia.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*result).Sup.kind; (*result).Sup.kind = copyStringRC1(((NimStringDesc*) &TM_QXH8VU509af4FifdjedxZFA_9));
	if (T1_) nimGCunrefNoCycle(T1_);
	nimln_(33, "inputmedia.nim");
	T2_ = (NimStringDesc*)0;
	T2_ = (*result).Sup.media; (*result).Sup.media = copyStringRC1(media);
	if (T2_) nimGCunrefNoCycle(T2_);
	nimln_(34, "inputmedia.nim");
	{
		if (!(((NI) 0) < (caption ? caption->Sup.len : 0))) goto LA5_;
		nimln_(35, "inputmedia.nim");
		some_SwTVedX6u26EmBXAZK9aBGQ(caption, (&(*result).Sup.caption));
	}
	LA5_: ;
	nimln_(36, "inputmedia.nim");
	{
		if (!(((NI) 0) < (parseMode ? parseMode->Sup.len : 0))) goto LA9_;
		nimln_(37, "inputmedia.nim");
		some_SwTVedX6u26EmBXAZK9aBGQ(parseMode, (&(*result).Sup.parseMode));
	}
	LA9_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isSet_8PWlY8kKGx8aCdLMEwqrqgutils)(NimStringDesc* value) {
	NIM_BOOL result;
	nimfr_("isSet", "utils.nim");
	result = (NIM_BOOL)0;
	nimln_(41, "utils.nim");
	result = (((NI) 0) < (value ? value->Sup.len : 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isSet_c1CqxABvDHekt9adqRAlPOAutils)(NI value) {
	NIM_BOOL result;
	nimfr_("isSet", "utils.nim");
	result = (NIM_BOOL)0;
	nimln_(43, "utils.nim");
	nimln_(398, "system.nim");
	nimln_(43, "utils.nim");
	result = !((value == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isSet_IBcRMEnyISyQB5bbGEgm1gutils)(NIM_BOOL value) {
	NIM_BOOL result;
	nimfr_("isSet", "utils.nim");
	result = (NIM_BOOL)0;
	nimln_(45, "utils.nim");
	result = value;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, telebot_inputmediaInit000)(void) {
	nimfr_("inputmedia", "inputmedia.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, telebot_inputmediaDatInit000)(void) {
}

