[package]
name = "we-have-time"
version = "0.1.0"
authors = ["Nicolas Modrzyk <nico@karabiner-software.com>"]

[dependencies]
chrono = "0.4.6"

[[bin]]
name = "main1"
path = "src/main.rs"

[[bin]]
name = "main2"
path = "src/main2.rs"
