{application,telegram,
             [{applications,[kernel,stdlib,elixir,logger,jason,hackney,tesla]},
              {description,"telegram"},
              {modules,['Elixir.Telegram.Api','Elixir.Telegram.Bot',
                        'Elixir.Telegram.Bot.Context',
                        'Elixir.Telegram.Bot.Dsl','Elixir.Telegram.Bot.Halt',
                        'Elixir.Telegram.Client']},
              {registered,[]},
              {vsn,"0.5.0"}]}.
